// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dateport_update_C5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S4_y_address0,
        S4_y_ce0,
        S4_y_q0,
        S4_y_address1,
        S4_y_ce1,
        S4_y_q1,
        C5_dmapData_address0,
        C5_dmapData_ce0,
        C5_dmapData_we0,
        C5_dmapData_d0,
        C5_dmapData_q0,
        C5_d_address0,
        C5_d_ce0,
        C5_d_q0,
        C5_dbias_address0,
        C5_dbias_ce0,
        C5_dbias_we0,
        C5_dbias_d0,
        C5_dbias_q0
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 24'b1;
parameter    ap_ST_st2_fsm_1 = 24'b10;
parameter    ap_ST_st3_fsm_2 = 24'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 24'b1000;
parameter    ap_ST_pp0_stg1_fsm_4 = 24'b10000;
parameter    ap_ST_pp0_stg2_fsm_5 = 24'b100000;
parameter    ap_ST_st11_fsm_6 = 24'b1000000;
parameter    ap_ST_st12_fsm_7 = 24'b10000000;
parameter    ap_ST_st13_fsm_8 = 24'b100000000;
parameter    ap_ST_st14_fsm_9 = 24'b1000000000;
parameter    ap_ST_st15_fsm_10 = 24'b10000000000;
parameter    ap_ST_st16_fsm_11 = 24'b100000000000;
parameter    ap_ST_st17_fsm_12 = 24'b1000000000000;
parameter    ap_ST_st18_fsm_13 = 24'b10000000000000;
parameter    ap_ST_st19_fsm_14 = 24'b100000000000000;
parameter    ap_ST_st20_fsm_15 = 24'b1000000000000000;
parameter    ap_ST_st21_fsm_16 = 24'b10000000000000000;
parameter    ap_ST_st22_fsm_17 = 24'b100000000000000000;
parameter    ap_ST_st23_fsm_18 = 24'b1000000000000000000;
parameter    ap_ST_st24_fsm_19 = 24'b10000000000000000000;
parameter    ap_ST_st25_fsm_20 = 24'b100000000000000000000;
parameter    ap_ST_st26_fsm_21 = 24'b1000000000000000000000;
parameter    ap_ST_st27_fsm_22 = 24'b10000000000000000000000;
parameter    ap_ST_st28_fsm_23 = 24'b100000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv9_1E0 = 9'b111100000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv6_2 = 6'b10;
parameter    ap_const_lv6_3 = 6'b11;
parameter    ap_const_lv6_4 = 6'b100;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv5_1E = 5'b11110;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] S4_y_address0;
output   S4_y_ce0;
input  [31:0] S4_y_q0;
output  [8:0] S4_y_address1;
output   S4_y_ce1;
input  [31:0] S4_y_q1;
output  [13:0] C5_dmapData_address0;
output   C5_dmapData_ce0;
output   C5_dmapData_we0;
output  [31:0] C5_dmapData_d0;
input  [31:0] C5_dmapData_q0;
output  [4:0] C5_d_address0;
output   C5_d_ce0;
input  [31:0] C5_d_q0;
output  [4:0] C5_dbias_address0;
output   C5_dbias_ce0;
output   C5_dbias_we0;
output  [31:0] C5_dbias_d0;
input  [31:0] C5_dbias_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] S4_y_address0;
reg S4_y_ce0;
reg[8:0] S4_y_address1;
reg S4_y_ce1;
reg[13:0] C5_dmapData_address0;
reg C5_dmapData_ce0;
reg C5_dmapData_we0;
reg[4:0] C5_d_address0;
reg C5_d_ce0;
reg[4:0] C5_dbias_address0;
reg C5_dbias_ce0;
reg C5_dbias_we0;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm = 24'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_42;
reg   [2:0] k_reg_263;
reg   [31:0] reg_325;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_86;
reg    ap_sig_cseq_ST_st22_fsm_17;
reg    ap_sig_bdd_93;
wire   [31:0] grp_fu_307_p2;
reg   [31:0] reg_332;
reg    ap_sig_cseq_ST_st19_fsm_14;
reg    ap_sig_bdd_103;
reg    ap_sig_cseq_ST_st27_fsm_22;
reg    ap_sig_bdd_110;
wire   [8:0] indvar_flatten_next_fu_344_p2;
reg   [8:0] indvar_flatten_next_reg_732;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_120;
wire   [4:0] j_mid2_fu_356_p3;
reg   [4:0] j_mid2_reg_737;
wire   [0:0] exitcond_flatten_fu_338_p2;
wire   [4:0] i_mid2_fu_370_p3;
reg   [4:0] i_mid2_reg_745;
wire   [9:0] tmp_154_trn_cast1_fu_383_p1;
reg   [9:0] tmp_154_trn_cast1_reg_756;
wire   [7:0] S4_y_addr9_fu_400_p2;
reg   [7:0] S4_y_addr9_reg_761;
wire   [0:0] exitcond4_fu_406_p2;
reg   [0:0] exitcond4_reg_766;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_bdd_143;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond4_reg_766_pp0_it1;
wire   [2:0] k_16_fu_412_p2;
reg   [2:0] k_16_reg_770;
wire   [31:0] S4_y_addr2_fu_447_p2;
reg   [31:0] S4_y_addr2_reg_775;
wire   [5:0] p_addr16_fu_470_p2;
reg   [5:0] p_addr16_reg_787;
reg   [5:0] ap_reg_ppstg_p_addr16_reg_787_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_4;
reg    ap_sig_bdd_174;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_5;
reg    ap_sig_bdd_189;
wire   [31:0] C5_dmapData_addr3_fu_593_p2;
reg   [31:0] C5_dmapData_addr3_reg_841;
reg    ap_sig_cseq_ST_st11_fsm_6;
reg    ap_sig_bdd_204;
wire   [2:0] k_17_fu_605_p2;
reg   [2:0] k_17_reg_849;
reg    ap_sig_cseq_ST_st12_fsm_7;
reg    ap_sig_bdd_213;
wire   [31:0] C5_dmapData_addr5_fu_632_p2;
reg   [31:0] C5_dmapData_addr5_reg_854;
wire   [0:0] exitcond2_fu_599_p2;
wire   [5:0] p_addr_fu_654_p2;
reg   [5:0] p_addr_reg_859;
wire   [4:0] j_16_fu_660_p2;
wire   [2:0] m_fu_671_p2;
reg   [2:0] m_reg_872;
reg    ap_sig_cseq_ST_st13_fsm_8;
reg    ap_sig_bdd_233;
reg   [13:0] C5_dmapData_addr_reg_877;
wire   [0:0] exitcond1_fu_665_p2;
reg   [31:0] C5_dmapData_load_reg_887;
reg    ap_sig_cseq_ST_st14_fsm_9;
reg    ap_sig_bdd_248;
wire   [31:0] tmp_q1;
reg   [31:0] empty_69_reg_892;
wire   [4:0] i_19_fu_717_p2;
reg   [4:0] i_19_reg_900;
reg    ap_sig_cseq_ST_st21_fsm_16;
reg    ap_sig_bdd_259;
reg   [4:0] C5_dbias_addr_reg_905;
wire   [0:0] exitcond_fu_711_p2;
reg   [31:0] C5_dbias_load_reg_915;
reg   [4:0] tmp_address0;
reg    tmp_ce0;
reg    tmp_we0;
reg   [31:0] tmp_d0;
reg   [4:0] tmp_address1;
reg    tmp_ce1;
reg    tmp_we1;
reg   [31:0] tmp_d1;
reg   [8:0] indvar_flatten_reg_230;
reg   [4:0] i_reg_241;
reg   [4:0] j_reg_252;
reg   [2:0] k_phi_fu_267_p4;
reg   [2:0] k_1_reg_274;
reg   [2:0] m_1_reg_285;
reg    ap_sig_cseq_ST_st20_fsm_15;
reg    ap_sig_bdd_313;
reg   [4:0] i_1_reg_296;
reg    ap_sig_cseq_ST_st28_fsm_23;
reg    ap_sig_bdd_322;
wire   [63:0] tmp_s_fu_378_p1;
wire   [63:0] tmp_191_fu_453_p1;
wire   [63:0] tmp_194_fu_482_p1;
wire   [63:0] tmp_196_fu_492_p1;
wire   [63:0] tmp_198_fu_502_p1;
wire   [63:0] tmp_200_fu_512_p1;
wire   [63:0] tmp_193_fu_517_p1;
wire   [63:0] tmp_195_fu_526_p1;
wire   [63:0] tmp_197_fu_536_p1;
wire   [63:0] tmp_199_fu_546_p1;
wire   [63:0] tmp_201_fu_556_p1;
wire   [63:0] tmp_203_fu_686_p1;
wire   [63:0] tmp_204_fu_706_p1;
wire   [63:0] tmp_98_fu_723_p1;
wire   [31:0] grp_fu_311_p2;
wire   [31:0] grp_fu_317_p2;
reg   [31:0] grp_fu_307_p0;
reg   [31:0] grp_fu_307_p1;
reg    ap_sig_cseq_ST_st15_fsm_10;
reg    ap_sig_bdd_380;
reg    ap_sig_cseq_ST_st23_fsm_18;
reg    ap_sig_bdd_387;
wire   [31:0] grp_fu_311_p0;
wire   [31:0] grp_fu_311_p1;
wire   [31:0] grp_fu_317_p0;
wire   [31:0] grp_fu_317_p1;
wire   [0:0] exitcond16_fu_350_p2;
wire   [4:0] i_4_fu_364_p2;
wire   [6:0] tmp_189_fu_389_p3;
wire   [7:0] tmp_154_trn_cast_fu_386_p1;
wire   [7:0] p_shl_cast_fu_396_p1;
wire   [7:0] tmp_155_trn_cast_fu_422_p1;
wire   [7:0] S4_y_addr1_fu_426_p2;
wire   [9:0] tmp_133_fu_435_p3;
wire   [31:0] S4_y_addr10_cast_fu_431_p1;
wire   [31:0] p_shl43_fu_443_p1;
wire   [4:0] tmp_192_fu_458_p3;
wire   [5:0] tmp_155_trn_cast1_fu_418_p1;
wire   [5:0] p_shl55_cast_fu_466_p1;
wire   [31:0] S4_y_addr3_fu_476_p2;
wire   [31:0] S4_y_addr4_fu_487_p2;
wire   [31:0] S4_y_addr5_fu_497_p2;
wire   [31:0] S4_y_addr6_fu_507_p2;
wire   [5:0] p_addr14_fu_521_p2;
wire   [5:0] p_addr11_fu_531_p2;
wire   [5:0] p_addr8_fu_541_p2;
wire   [5:0] p_addr5_fu_551_p2;
wire   [8:0] tmp_190_fu_561_p3;
wire   [9:0] C5_dmapData_addr1_cast_fu_568_p1;
wire   [9:0] C5_dmapData_addr2_fu_572_p2;
wire   [11:0] tmp_132_fu_581_p3;
wire   [31:0] p_shl_fu_589_p1;
wire   [31:0] C5_dmapData_addr2_cast_fu_577_p1;
wire   [31:0] tmp_157_trn_fu_617_p1;
wire   [31:0] C5_dmapData_addr4_fu_621_p2;
wire   [31:0] tmp_134_fu_626_p2;
wire  signed [2:0] tmp_101_fu_611_p2;
wire   [4:0] tmp_202_fu_642_p3;
wire   [5:0] p_shl57_cast_fu_650_p1;
wire   [5:0] tmp_159_trn_cast_fu_638_p1;
wire   [31:0] tmp_160_trn_fu_677_p1;
wire   [31:0] C5_dmapData_addr6_fu_681_p2;
wire  signed [2:0] tmp_102_fu_691_p2;
wire   [5:0] tmp_162_trn_cast_fu_697_p1;
wire   [5:0] p_addr3_fu_701_p2;
wire    grp_fu_307_ce;
wire    grp_fu_311_ce;
wire    grp_fu_317_ce;
reg   [23:0] ap_NS_fsm;


dateport_update_C5_tmp #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
tmp_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( tmp_address0 ),
    .ce0( tmp_ce0 ),
    .we0( tmp_we0 ),
    .d0( tmp_d0 ),
    .address1( tmp_address1 ),
    .ce1( tmp_ce1 ),
    .we1( tmp_we1 ),
    .d1( tmp_d1 ),
    .q1( tmp_q1 )
);

dateport_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dateport_fadd_32ns_32ns_32_5_full_dsp_U93(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_307_p0 ),
    .din1( grp_fu_307_p1 ),
    .ce( grp_fu_307_ce ),
    .dout( grp_fu_307_p2 )
);

dateport_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dateport_fmul_32ns_32ns_32_4_max_dsp_U94(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_311_p0 ),
    .din1( grp_fu_311_p1 ),
    .ce( grp_fu_311_ce ),
    .dout( grp_fu_311_p2 )
);

dateport_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dateport_fmul_32ns_32ns_32_4_max_dsp_U95(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_317_p0 ),
    .din1( grp_fu_317_p1 ),
    .ce( grp_fu_317_ce ),
    .dout( grp_fu_317_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == exitcond4_fu_406_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond4_reg_766) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & ~(ap_const_lv1_0 == exitcond4_reg_766)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond_flatten_fu_338_p2 == ap_const_lv1_0))) begin
        i_1_reg_296 <= ap_const_lv5_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_23)) begin
        i_1_reg_296 <= i_19_reg_900;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_7) & ~(ap_const_lv1_0 == exitcond2_fu_599_p2))) begin
        i_reg_241 <= i_mid2_reg_745;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        i_reg_241 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_7) & ~(ap_const_lv1_0 == exitcond2_fu_599_p2))) begin
        indvar_flatten_reg_230 <= indvar_flatten_next_reg_732;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        indvar_flatten_reg_230 <= ap_const_lv9_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_7) & ~(ap_const_lv1_0 == exitcond2_fu_599_p2))) begin
        j_reg_252 <= j_16_fu_660_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        j_reg_252 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8) & ~(ap_const_lv1_0 == exitcond1_fu_665_p2))) begin
        k_1_reg_274 <= k_17_reg_849;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_6)) begin
        k_1_reg_274 <= ap_const_lv3_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        k_reg_263 <= ap_const_lv3_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_lv1_0 == exitcond4_reg_766))) begin
        k_reg_263 <= k_16_reg_770;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_7) & (ap_const_lv1_0 == exitcond2_fu_599_p2))) begin
        m_1_reg_285 <= ap_const_lv3_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_15)) begin
        m_1_reg_285 <= m_reg_872;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16) & (ap_const_lv1_0 == exitcond_fu_711_p2))) begin
        C5_dbias_addr_reg_905 <= tmp_98_fu_723_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_17)) begin
        C5_dbias_load_reg_915 <= C5_dbias_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_6)) begin
        C5_dmapData_addr3_reg_841 <= C5_dmapData_addr3_fu_593_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_7) & (ap_const_lv1_0 == exitcond2_fu_599_p2))) begin
        C5_dmapData_addr5_reg_854 <= C5_dmapData_addr5_fu_632_p2;
        p_addr_reg_859 <= p_addr_fu_654_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8) & (ap_const_lv1_0 == exitcond1_fu_665_p2))) begin
        C5_dmapData_addr_reg_877 <= tmp_203_fu_686_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_9)) begin
        C5_dmapData_load_reg_887 <= C5_dmapData_q0;
        empty_69_reg_892 <= tmp_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_lv1_0 == exitcond4_fu_406_p2))) begin
        S4_y_addr2_reg_775 <= S4_y_addr2_fu_447_p2;
        p_addr16_reg_787 <= p_addr16_fu_470_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        S4_y_addr9_reg_761 <= S4_y_addr9_fu_400_p2;
        tmp_154_trn_cast1_reg_756[4 : 0] <= tmp_154_trn_cast1_fu_383_p1[4 : 0];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3)) begin
        ap_reg_ppstg_exitcond4_reg_766_pp0_it1 <= exitcond4_reg_766;
        ap_reg_ppstg_p_addr16_reg_787_pp0_it1 <= p_addr16_reg_787;
        exitcond4_reg_766 <= exitcond4_fu_406_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16)) begin
        i_19_reg_900 <= i_19_fu_717_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_flatten_fu_338_p2 == ap_const_lv1_0))) begin
        i_mid2_reg_745 <= i_mid2_fu_370_p3;
        j_mid2_reg_737 <= j_mid2_fu_356_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        indvar_flatten_next_reg_732 <= indvar_flatten_next_fu_344_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        k_16_reg_770 <= k_16_fu_412_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_7)) begin
        k_17_reg_849 <= k_17_fu_605_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8)) begin
        m_reg_872 <= m_fu_671_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_17))) begin
        reg_325 <= C5_d_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_22))) begin
        reg_332 <= grp_fu_307_p2;
    end
end

/// C5_d_address0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st21_fsm_16 or tmp_s_fu_378_p1 or tmp_98_fu_723_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16)) begin
        C5_d_address0 = tmp_98_fu_723_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        C5_d_address0 = tmp_s_fu_378_p1;
    end else begin
        C5_d_address0 = 'bx;
    end
end

/// C5_d_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st21_fsm_16)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16))) begin
        C5_d_ce0 = ap_const_logic_1;
    end else begin
        C5_d_ce0 = ap_const_logic_0;
    end
end

/// C5_dbias_address0 assign process. ///
always @ (ap_sig_cseq_ST_st21_fsm_16 or C5_dbias_addr_reg_905 or ap_sig_cseq_ST_st28_fsm_23 or tmp_98_fu_723_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_23)) begin
        C5_dbias_address0 = C5_dbias_addr_reg_905;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16)) begin
        C5_dbias_address0 = tmp_98_fu_723_p1;
    end else begin
        C5_dbias_address0 = 'bx;
    end
end

/// C5_dbias_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st21_fsm_16 or ap_sig_cseq_ST_st28_fsm_23)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16) | (ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_23))) begin
        C5_dbias_ce0 = ap_const_logic_1;
    end else begin
        C5_dbias_ce0 = ap_const_logic_0;
    end
end

/// C5_dbias_we0 assign process. ///
always @ (ap_sig_cseq_ST_st28_fsm_23)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_23)) begin
        C5_dbias_we0 = ap_const_logic_1;
    end else begin
        C5_dbias_we0 = ap_const_logic_0;
    end
end

/// C5_dmapData_address0 assign process. ///
always @ (ap_sig_cseq_ST_st13_fsm_8 or C5_dmapData_addr_reg_877 or ap_sig_cseq_ST_st20_fsm_15 or tmp_203_fu_686_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_15)) begin
        C5_dmapData_address0 = C5_dmapData_addr_reg_877;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8)) begin
        C5_dmapData_address0 = tmp_203_fu_686_p1;
    end else begin
        C5_dmapData_address0 = 'bx;
    end
end

/// C5_dmapData_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st13_fsm_8 or ap_sig_cseq_ST_st20_fsm_15)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_15))) begin
        C5_dmapData_ce0 = ap_const_logic_1;
    end else begin
        C5_dmapData_ce0 = ap_const_logic_0;
    end
end

/// C5_dmapData_we0 assign process. ///
always @ (ap_sig_cseq_ST_st20_fsm_15)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_15)) begin
        C5_dmapData_we0 = ap_const_logic_1;
    end else begin
        C5_dmapData_we0 = ap_const_logic_0;
    end
end

/// S4_y_address0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5 or tmp_191_fu_453_p1 or tmp_196_fu_492_p1 or tmp_200_fu_512_p1)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5)) begin
            S4_y_address0 = tmp_200_fu_512_p1;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) begin
            S4_y_address0 = tmp_196_fu_492_p1;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3)) begin
            S4_y_address0 = tmp_191_fu_453_p1;
        end else begin
            S4_y_address0 = 'bx;
        end
    end else begin
        S4_y_address0 = 'bx;
    end
end

/// S4_y_address1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or tmp_194_fu_482_p1 or tmp_198_fu_502_p1)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) begin
            S4_y_address1 = tmp_198_fu_502_p1;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3)) begin
            S4_y_address1 = tmp_194_fu_482_p1;
        end else begin
            S4_y_address1 = 'bx;
        end
    end else begin
        S4_y_address1 = 'bx;
    end
end

/// S4_y_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5)))) begin
        S4_y_ce0 = ap_const_logic_1;
    end else begin
        S4_y_ce0 = ap_const_logic_0;
    end
end

/// S4_y_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_4)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)))) begin
        S4_y_ce1 = ap_const_logic_1;
    end else begin
        S4_y_ce1 = ap_const_logic_0;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st21_fsm_16 or exitcond_fu_711_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16) & ~(ap_const_lv1_0 == exitcond_fu_711_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st21_fsm_16 or exitcond_fu_711_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_16) & ~(ap_const_lv1_0 == exitcond_fu_711_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_3 assign process. ///
always @ (ap_sig_bdd_143)
begin
    if (ap_sig_bdd_143) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg1_fsm_4 assign process. ///
always @ (ap_sig_bdd_174)
begin
    if (ap_sig_bdd_174) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg2_fsm_5 assign process. ///
always @ (ap_sig_bdd_189)
begin
    if (ap_sig_bdd_189) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_6 assign process. ///
always @ (ap_sig_bdd_204)
begin
    if (ap_sig_bdd_204) begin
        ap_sig_cseq_ST_st11_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_7 assign process. ///
always @ (ap_sig_bdd_213)
begin
    if (ap_sig_bdd_213) begin
        ap_sig_cseq_ST_st12_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st13_fsm_8 assign process. ///
always @ (ap_sig_bdd_233)
begin
    if (ap_sig_bdd_233) begin
        ap_sig_cseq_ST_st13_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_8 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st14_fsm_9 assign process. ///
always @ (ap_sig_bdd_248)
begin
    if (ap_sig_bdd_248) begin
        ap_sig_cseq_ST_st14_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st15_fsm_10 assign process. ///
always @ (ap_sig_bdd_380)
begin
    if (ap_sig_bdd_380) begin
        ap_sig_cseq_ST_st15_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st19_fsm_14 assign process. ///
always @ (ap_sig_bdd_103)
begin
    if (ap_sig_bdd_103) begin
        ap_sig_cseq_ST_st19_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_14 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_42)
begin
    if (ap_sig_bdd_42) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st20_fsm_15 assign process. ///
always @ (ap_sig_bdd_313)
begin
    if (ap_sig_bdd_313) begin
        ap_sig_cseq_ST_st20_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_15 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st21_fsm_16 assign process. ///
always @ (ap_sig_bdd_259)
begin
    if (ap_sig_bdd_259) begin
        ap_sig_cseq_ST_st21_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_16 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st22_fsm_17 assign process. ///
always @ (ap_sig_bdd_93)
begin
    if (ap_sig_bdd_93) begin
        ap_sig_cseq_ST_st22_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_17 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st23_fsm_18 assign process. ///
always @ (ap_sig_bdd_387)
begin
    if (ap_sig_bdd_387) begin
        ap_sig_cseq_ST_st23_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st23_fsm_18 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st27_fsm_22 assign process. ///
always @ (ap_sig_bdd_110)
begin
    if (ap_sig_bdd_110) begin
        ap_sig_cseq_ST_st27_fsm_22 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st27_fsm_22 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st28_fsm_23 assign process. ///
always @ (ap_sig_bdd_322)
begin
    if (ap_sig_bdd_322) begin
        ap_sig_cseq_ST_st28_fsm_23 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st28_fsm_23 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_120)
begin
    if (ap_sig_bdd_120) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_86)
begin
    if (ap_sig_bdd_86) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// grp_fu_307_p0 assign process. ///
always @ (C5_dmapData_load_reg_887 or C5_dbias_load_reg_915 or ap_sig_cseq_ST_st15_fsm_10 or ap_sig_cseq_ST_st23_fsm_18)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st23_fsm_18)) begin
        grp_fu_307_p0 = C5_dbias_load_reg_915;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_10)) begin
        grp_fu_307_p0 = C5_dmapData_load_reg_887;
    end else begin
        grp_fu_307_p0 = 'bx;
    end
end

/// grp_fu_307_p1 assign process. ///
always @ (reg_325 or empty_69_reg_892 or ap_sig_cseq_ST_st15_fsm_10 or ap_sig_cseq_ST_st23_fsm_18)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st23_fsm_18)) begin
        grp_fu_307_p1 = reg_325;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_10)) begin
        grp_fu_307_p1 = empty_69_reg_892;
    end else begin
        grp_fu_307_p1 = 'bx;
    end
end

/// k_phi_fu_267_p4 assign process. ///
always @ (k_reg_263 or exitcond4_reg_766 or ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or k_16_reg_770)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_lv1_0 == exitcond4_reg_766))) begin
        k_phi_fu_267_p4 = k_16_reg_770;
    end else begin
        k_phi_fu_267_p4 = k_reg_263;
    end
end

/// tmp_address0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5 or tmp_193_fu_517_p1 or tmp_199_fu_546_p1 or tmp_201_fu_556_p1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) begin
        tmp_address0 = tmp_201_fu_556_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        tmp_address0 = tmp_199_fu_546_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4))) begin
        tmp_address0 = tmp_193_fu_517_p1;
    end else begin
        tmp_address0 = 'bx;
    end
end

/// tmp_address1 assign process. ///
always @ (ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5 or ap_sig_cseq_ST_st13_fsm_8 or tmp_195_fu_526_p1 or tmp_197_fu_536_p1 or tmp_204_fu_706_p1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        tmp_address1 = tmp_197_fu_536_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4))) begin
        tmp_address1 = tmp_195_fu_526_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8)) begin
        tmp_address1 = tmp_204_fu_706_p1;
    end else begin
        tmp_address1 = 'bx;
    end
end

/// tmp_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
        tmp_ce0 = ap_const_logic_1;
    end else begin
        tmp_ce0 = ap_const_logic_0;
    end
end

/// tmp_ce1 assign process. ///
always @ (ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5 or ap_sig_cseq_ST_st13_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_8) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5)))) begin
        tmp_ce1 = ap_const_logic_1;
    end else begin
        tmp_ce1 = ap_const_logic_0;
    end
end

/// tmp_d0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5 or grp_fu_311_p2 or grp_fu_317_p2)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        tmp_d0 = grp_fu_317_p2;
    end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
        tmp_d0 = grp_fu_311_p2;
    end else begin
        tmp_d0 = 'bx;
    end
end

/// tmp_d1 assign process. ///
always @ (ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5 or grp_fu_311_p2 or grp_fu_317_p2)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5)) begin
            tmp_d1 = grp_fu_311_p2;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4)) begin
            tmp_d1 = grp_fu_317_p2;
        end else begin
            tmp_d1 = 'bx;
        end
    end else begin
        tmp_d1 = 'bx;
    end
end

/// tmp_we0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond4_reg_766_pp0_it1 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_766_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_766_pp0_it1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_766_pp0_it1)))) begin
        tmp_we0 = ap_const_logic_1;
    end else begin
        tmp_we0 = ap_const_logic_0;
    end
end

/// tmp_we1 assign process. ///
always @ (ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond4_reg_766_pp0_it1 or ap_sig_cseq_ST_pp0_stg1_fsm_4 or ap_sig_cseq_ST_pp0_stg2_fsm_5)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_766_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_766_pp0_it1)))) begin
        tmp_we1 = ap_const_logic_1;
    end else begin
        tmp_we1 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or exitcond_flatten_fu_338_p2 or exitcond4_fu_406_p2 or ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or exitcond2_fu_599_p2 or exitcond1_fu_665_p2 or exitcond_fu_711_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond_flatten_fu_338_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st21_fsm_16;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if ((~((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond4_fu_406_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_4;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond4_fu_406_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_st11_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_6;
            end
        end
        ap_ST_pp0_stg1_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_5;
        end
        ap_ST_pp0_stg2_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_st11_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_7;
        end
        ap_ST_st12_fsm_7 : 
        begin
            if (~(ap_const_lv1_0 == exitcond2_fu_599_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_8;
            end
        end
        ap_ST_st13_fsm_8 : 
        begin
            if ((ap_const_lv1_0 == exitcond1_fu_665_p2)) begin
                ap_NS_fsm = ap_ST_st14_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_7;
            end
        end
        ap_ST_st14_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_10;
        end
        ap_ST_st15_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_11;
        end
        ap_ST_st16_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_12;
        end
        ap_ST_st17_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_13;
        end
        ap_ST_st18_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_14;
        end
        ap_ST_st19_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st20_fsm_15;
        end
        ap_ST_st20_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_8;
        end
        ap_ST_st21_fsm_16 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_fu_711_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st22_fsm_17;
            end
        end
        ap_ST_st22_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st23_fsm_18;
        end
        ap_ST_st23_fsm_18 : 
        begin
            ap_NS_fsm = ap_ST_st24_fsm_19;
        end
        ap_ST_st24_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st25_fsm_20;
        end
        ap_ST_st25_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_st26_fsm_21;
        end
        ap_ST_st26_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st27_fsm_22;
        end
        ap_ST_st27_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_st28_fsm_23;
        end
        ap_ST_st28_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_st21_fsm_16;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C5_dbias_d0 = reg_332;
assign C5_dmapData_addr1_cast_fu_568_p1 = tmp_190_fu_561_p3;
assign C5_dmapData_addr2_cast_fu_577_p1 = C5_dmapData_addr2_fu_572_p2;
assign C5_dmapData_addr2_fu_572_p2 = (tmp_154_trn_cast1_reg_756 + C5_dmapData_addr1_cast_fu_568_p1);
assign C5_dmapData_addr3_fu_593_p2 = (p_shl_fu_589_p1 + C5_dmapData_addr2_cast_fu_577_p1);
assign C5_dmapData_addr4_fu_621_p2 = (tmp_157_trn_fu_617_p1 + C5_dmapData_addr3_reg_841);
assign C5_dmapData_addr5_fu_632_p2 = (tmp_134_fu_626_p2 + C5_dmapData_addr4_fu_621_p2);
assign C5_dmapData_addr6_fu_681_p2 = (tmp_160_trn_fu_677_p1 + C5_dmapData_addr5_reg_854);
assign C5_dmapData_d0 = reg_332;
assign S4_y_addr10_cast_fu_431_p1 = S4_y_addr1_fu_426_p2;
assign S4_y_addr1_fu_426_p2 = (S4_y_addr9_reg_761 + tmp_155_trn_cast_fu_422_p1);
assign S4_y_addr2_fu_447_p2 = (S4_y_addr10_cast_fu_431_p1 + p_shl43_fu_443_p1);
assign S4_y_addr3_fu_476_p2 = (S4_y_addr2_fu_447_p2 + ap_const_lv32_1);
assign S4_y_addr4_fu_487_p2 = (S4_y_addr2_reg_775 + ap_const_lv32_2);
assign S4_y_addr5_fu_497_p2 = (S4_y_addr2_reg_775 + ap_const_lv32_3);
assign S4_y_addr6_fu_507_p2 = (S4_y_addr2_reg_775 + ap_const_lv32_4);
assign S4_y_addr9_fu_400_p2 = (tmp_154_trn_cast_fu_386_p1 + p_shl_cast_fu_396_p1);

/// ap_sig_bdd_103 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_103 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end

/// ap_sig_bdd_110 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_110 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_16]);
end

/// ap_sig_bdd_120 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_120 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_143 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_143 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_174 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_174 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_189 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_189 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_204 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_204 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_213 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_213 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_233 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_233 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_248 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_248 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_259 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_259 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end

/// ap_sig_bdd_313 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_313 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end

/// ap_sig_bdd_322 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_322 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_17]);
end

/// ap_sig_bdd_380 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_380 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_387 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_387 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end

/// ap_sig_bdd_42 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_42 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_86 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_86 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_93 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_93 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end
assign exitcond16_fu_350_p2 = (j_reg_252 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond1_fu_665_p2 = (m_1_reg_285 == ap_const_lv3_5? 1'b1: 1'b0);
assign exitcond2_fu_599_p2 = (k_1_reg_274 == ap_const_lv3_5? 1'b1: 1'b0);
assign exitcond4_fu_406_p2 = (k_phi_fu_267_p4 == ap_const_lv3_5? 1'b1: 1'b0);
assign exitcond_flatten_fu_338_p2 = (indvar_flatten_reg_230 == ap_const_lv9_1E0? 1'b1: 1'b0);
assign exitcond_fu_711_p2 = (i_1_reg_296 == ap_const_lv5_1E? 1'b1: 1'b0);
assign grp_fu_307_ce = ap_const_logic_1;
assign grp_fu_311_ce = ap_const_logic_1;
assign grp_fu_311_p0 = S4_y_q0;
assign grp_fu_311_p1 = reg_325;
assign grp_fu_317_ce = ap_const_logic_1;
assign grp_fu_317_p0 = S4_y_q1;
assign grp_fu_317_p1 = reg_325;
assign i_19_fu_717_p2 = (i_1_reg_296 + ap_const_lv5_1);
assign i_4_fu_364_p2 = (i_reg_241 + ap_const_lv5_1);
assign i_mid2_fu_370_p3 = ((exitcond16_fu_350_p2[0:0]===1'b1)? i_4_fu_364_p2: i_reg_241);
assign indvar_flatten_next_fu_344_p2 = (indvar_flatten_reg_230 + ap_const_lv9_1);
assign j_16_fu_660_p2 = (j_mid2_reg_737 + ap_const_lv5_1);
assign j_mid2_fu_356_p3 = ((exitcond16_fu_350_p2[0:0]===1'b1)? ap_const_lv5_0: j_reg_252);
assign k_16_fu_412_p2 = (k_phi_fu_267_p4 + ap_const_lv3_1);
assign k_17_fu_605_p2 = (k_1_reg_274 + ap_const_lv3_1);
assign m_fu_671_p2 = (m_1_reg_285 + ap_const_lv3_1);
assign p_addr11_fu_531_p2 = (ap_reg_ppstg_p_addr16_reg_787_pp0_it1 + ap_const_lv6_2);
assign p_addr14_fu_521_p2 = (ap_reg_ppstg_p_addr16_reg_787_pp0_it1 + ap_const_lv6_1);
assign p_addr16_fu_470_p2 = (tmp_155_trn_cast1_fu_418_p1 + p_shl55_cast_fu_466_p1);
assign p_addr3_fu_701_p2 = (tmp_162_trn_cast_fu_697_p1 + p_addr_reg_859);
assign p_addr5_fu_551_p2 = (ap_reg_ppstg_p_addr16_reg_787_pp0_it1 + ap_const_lv6_4);
assign p_addr8_fu_541_p2 = (ap_reg_ppstg_p_addr16_reg_787_pp0_it1 + ap_const_lv6_3);
assign p_addr_fu_654_p2 = (p_shl57_cast_fu_650_p1 + tmp_159_trn_cast_fu_638_p1);
assign p_shl43_fu_443_p1 = tmp_133_fu_435_p3;
assign p_shl55_cast_fu_466_p1 = tmp_192_fu_458_p3;
assign p_shl57_cast_fu_650_p1 = tmp_202_fu_642_p3;
assign p_shl_cast_fu_396_p1 = tmp_189_fu_389_p3;
assign p_shl_fu_589_p1 = tmp_132_fu_581_p3;
assign tmp_101_fu_611_p2 = ($signed(ap_const_lv3_4) - $signed(k_1_reg_274));
assign tmp_102_fu_691_p2 = ($signed(ap_const_lv3_4) - $signed(m_1_reg_285));
assign tmp_132_fu_581_p3 = {{C5_dmapData_addr2_fu_572_p2}, {ap_const_lv2_0}};
assign tmp_133_fu_435_p3 = {{S4_y_addr1_fu_426_p2}, {ap_const_lv2_0}};
assign tmp_134_fu_626_p2 = C5_dmapData_addr4_fu_621_p2 << ap_const_lv32_2;
assign tmp_154_trn_cast1_fu_383_p1 = j_mid2_reg_737;
assign tmp_154_trn_cast_fu_386_p1 = j_mid2_reg_737;
assign tmp_155_trn_cast1_fu_418_p1 = k_phi_fu_267_p4;
assign tmp_155_trn_cast_fu_422_p1 = k_phi_fu_267_p4;
assign tmp_157_trn_fu_617_p1 = k_1_reg_274;
assign tmp_159_trn_cast_fu_638_p1 = $unsigned(tmp_101_fu_611_p2);
assign tmp_160_trn_fu_677_p1 = m_1_reg_285;
assign tmp_162_trn_cast_fu_697_p1 = $unsigned(tmp_102_fu_691_p2);
assign tmp_189_fu_389_p3 = {{j_mid2_reg_737}, {ap_const_lv2_0}};
assign tmp_190_fu_561_p3 = {{i_mid2_reg_745}, {ap_const_lv4_0}};
assign tmp_191_fu_453_p1 = S4_y_addr2_fu_447_p2;
assign tmp_192_fu_458_p3 = {{k_phi_fu_267_p4}, {ap_const_lv2_0}};
assign tmp_193_fu_517_p1 = ap_reg_ppstg_p_addr16_reg_787_pp0_it1;
assign tmp_194_fu_482_p1 = S4_y_addr3_fu_476_p2;
assign tmp_195_fu_526_p1 = p_addr14_fu_521_p2;
assign tmp_196_fu_492_p1 = S4_y_addr4_fu_487_p2;
assign tmp_197_fu_536_p1 = p_addr11_fu_531_p2;
assign tmp_198_fu_502_p1 = S4_y_addr5_fu_497_p2;
assign tmp_199_fu_546_p1 = p_addr8_fu_541_p2;
assign tmp_200_fu_512_p1 = S4_y_addr6_fu_507_p2;
assign tmp_201_fu_556_p1 = p_addr5_fu_551_p2;
assign tmp_202_fu_642_p3 = {{tmp_101_fu_611_p2}, {ap_const_lv2_0}};
assign tmp_203_fu_686_p1 = C5_dmapData_addr6_fu_681_p2;
assign tmp_204_fu_706_p1 = p_addr3_fu_701_p2;
assign tmp_98_fu_723_p1 = i_1_reg_296;
assign tmp_s_fu_378_p1 = i_mid2_fu_370_p3;
always @ (posedge ap_clk)
begin
    tmp_154_trn_cast1_reg_756[9:5] <= 5'b00000;
end



endmodule //dateport_update_C5

