// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "dateport_DC3_layer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dateport_DC3_layer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dateport_DC3_layer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> dateport_DC3_layer::ap_ST_st1_fsm_0 = "1";
const sc_lv<21> dateport_DC3_layer::ap_ST_st2_fsm_1 = "10";
const sc_lv<21> dateport_DC3_layer::ap_ST_st3_fsm_2 = "100";
const sc_lv<21> dateport_DC3_layer::ap_ST_st4_fsm_3 = "1000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st5_fsm_4 = "10000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st6_fsm_5 = "100000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<21> dateport_DC3_layer::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dateport_DC3_layer::ap_const_lv1_1 = "1";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_A = "1010";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_B = "1011";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_1 = "1";
const sc_lv<1> dateport_DC3_layer::ap_const_lv1_0 = "0";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_2 = "10";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_3 = "11";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_4 = "100";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_5 = "101";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_6 = "110";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_C = "1100";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_D = "1101";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_F = "1111";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_10 = "10000";
const sc_lv<5> dateport_DC3_layer::ap_const_lv5_0 = "00000";
const sc_lv<4> dateport_DC3_layer::ap_const_lv4_0 = "0000";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_14 = "10100";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_13 = "10011";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_7 = "111";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_3E800000 = "111110100000000000000000000000";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_11 = "10001";
const sc_lv<5> dateport_DC3_layer::ap_const_lv5_10 = "10000";
const sc_lv<5> dateport_DC3_layer::ap_const_lv5_1 = "1";
const sc_lv<2> dateport_DC3_layer::ap_const_lv2_0 = "00";
const sc_lv<3> dateport_DC3_layer::ap_const_lv3_0 = "000";
const sc_lv<4> dateport_DC3_layer::ap_const_lv4_A = "1010";
const sc_lv<4> dateport_DC3_layer::ap_const_lv4_1 = "1";
const sc_lv<4> dateport_DC3_layer::ap_const_lv4_2 = "10";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_17 = "10111";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_1E = "11110";
const sc_lv<8> dateport_DC3_layer::ap_const_lv8_FF = "11111111";
const sc_lv<23> dateport_DC3_layer::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> dateport_DC3_layer::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<5> dateport_DC3_layer::ap_const_lv5_2 = "10";

dateport_DC3_layer::dateport_DC3_layer(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54 = new dateport_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dateport_fadd_32ns_32ns_32_5_full_dsp_U54");
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54->clk(ap_clk);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54->reset(ap_rst);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54->din0(grp_fu_207_p0);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54->din1(grp_fu_207_p1);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54->ce(grp_fu_207_ce);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U54->dout(grp_fu_207_p2);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55 = new dateport_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dateport_fadd_32ns_32ns_32_5_full_dsp_U55");
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55->clk(ap_clk);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55->reset(ap_rst);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55->din0(grp_fu_211_p0);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55->din1(grp_fu_211_p1);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55->ce(grp_fu_211_ce);
    dateport_fadd_32ns_32ns_32_5_full_dsp_U55->dout(grp_fu_211_p2);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56 = new dateport_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("dateport_fmul_32ns_32ns_32_4_max_dsp_U56");
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56->clk(ap_clk);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56->reset(ap_rst);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56->din0(grp_fu_215_p0);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56->din1(grp_fu_215_p1);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56->ce(grp_fu_215_ce);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U56->dout(grp_fu_215_p2);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57 = new dateport_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("dateport_fmul_32ns_32ns_32_4_max_dsp_U57");
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57->clk(ap_clk);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57->reset(ap_rst);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57->din0(grp_fu_220_p0);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57->din1(grp_fu_220_p1);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57->ce(grp_fu_220_ce);
    dateport_fmul_32ns_32ns_32_4_max_dsp_U57->dout(grp_fu_220_p2);
    dateport_fcmp_32ns_32ns_1_1_U58 = new dateport_fcmp_32ns_32ns_1_1<1,1,32,32,1>("dateport_fcmp_32ns_32ns_1_1_U58");
    dateport_fcmp_32ns_32ns_1_1_U58->din0(grp_fu_229_p0);
    dateport_fcmp_32ns_32ns_1_1_U58->din1(grp_fu_229_p1);
    dateport_fcmp_32ns_32ns_1_1_U58->opcode(grp_fu_229_opcode);
    dateport_fcmp_32ns_32ns_1_1_U58->dout(grp_fu_229_p2);
    dateport_fcmp_32ns_32ns_1_1_U59 = new dateport_fcmp_32ns_32ns_1_1<1,1,32,32,1>("dateport_fcmp_32ns_32ns_1_1_U59");
    dateport_fcmp_32ns_32ns_1_1_U59->din0(grp_fu_234_p0);
    dateport_fcmp_32ns_32ns_1_1_U59->din1(grp_fu_234_p1);
    dateport_fcmp_32ns_32ns_1_1_U59->opcode(grp_fu_234_opcode);
    dateport_fcmp_32ns_32ns_1_1_U59->dout(grp_fu_234_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C3_bias_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_261_p1 );

    SC_METHOD(thread_C3_bias_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_C3_d_address0);
    sensitive << ( tmp_112_reg_800 );
    sensitive << ( tmp_114_reg_850 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_address1);
    sensitive << ( tmp_113_reg_810 );
    sensitive << ( tmp_115_reg_860 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_ce0);
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_ce1);
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_d0);
    sensitive << ( grp_fu_215_p2 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_d1);
    sensitive << ( grp_fu_220_p2 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_we0);
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_d_we1);
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_C3_y_addr10_fu_508_p2);
    sensitive << ( C3_y_addr9_reg_786 );
    sensitive << ( tmp_83_trn_fu_474_p1 );

    SC_METHOD(thread_C3_y_addr11_fu_478_p2);
    sensitive << ( C3_y_addr7_reg_780 );
    sensitive << ( tmp_83_trn_fu_474_p1 );

    SC_METHOD(thread_C3_y_addr12_fu_498_p2);
    sensitive << ( C3_y_addr7_reg_780 );
    sensitive << ( tmp_87_trn_fu_494_p1 );

    SC_METHOD(thread_C3_y_addr4_fu_513_p2);
    sensitive << ( C3_y_addr9_reg_786 );
    sensitive << ( tmp_87_trn_fu_494_p1 );

    SC_METHOD(thread_C3_y_addr5_fu_312_p2);
    sensitive << ( p_shl42_cast_fu_308_p1 );
    sensitive << ( p_shl_cast_fu_296_p1 );

    SC_METHOD(thread_C3_y_addr6_fu_375_p2);
    sensitive << ( C3_y_addr5_reg_766 );
    sensitive << ( tmp_77_trn_cast_fu_371_p1 );

    SC_METHOD(thread_C3_y_addr7_fu_404_p2);
    sensitive << ( p_shl16_fu_388_p1 );
    sensitive << ( p_shl17_fu_400_p1 );

    SC_METHOD(thread_C3_y_addr8_fu_414_p2);
    sensitive << ( C3_y_addr5_reg_766 );
    sensitive << ( tmp_79_trn6_cast_fu_410_p1 );

    SC_METHOD(thread_C3_y_addr9_fu_443_p2);
    sensitive << ( p_shl18_fu_427_p1 );
    sensitive << ( p_shl19_fu_439_p1 );

    SC_METHOD(thread_C3_y_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_112_fu_483_p1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_114_fu_530_p1 );

    SC_METHOD(thread_C3_y_address1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_113_fu_503_p1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_115_fu_534_p1 );

    SC_METHOD(thread_C3_y_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_C3_y_ce1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S4_d_addr12_fu_282_p2);
    sensitive << ( tmp_trn_cast_fu_266_p1 );
    sensitive << ( p_shl41_cast_fu_278_p1 );

    SC_METHOD(thread_S4_d_addr13_cast_fu_349_p1);
    sensitive << ( S4_d_addr13_fu_344_p2 );

    SC_METHOD(thread_S4_d_addr13_fu_344_p2);
    sensitive << ( S4_d_addr12_reg_761 );
    sensitive << ( tmp_76_trn_cast_fu_340_p1 );

    SC_METHOD(thread_S4_d_addr14_fu_365_p2);
    sensitive << ( p_shl_fu_361_p1 );
    sensitive << ( S4_d_addr13_cast_fu_349_p1 );

    SC_METHOD(thread_S4_d_addr15_fu_469_p2);
    sensitive << ( S4_d_addr14_reg_775 );
    sensitive << ( tmp_82_trn_fu_465_p1 );

    SC_METHOD(thread_S4_d_address0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_111_fu_538_p1 );

    SC_METHOD(thread_S4_d_ce0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_249_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_249_p2 );

    SC_METHOD(thread_ap_sig_bdd_102);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_116);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_129);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_146);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_175);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_192);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_207);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_224);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_235);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_245);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_265);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_275);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_289);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_302);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_90);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_90 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_207 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_224 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_bdd_235 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_245 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_302 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_39 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_275 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_bdd_265 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_102 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_116 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_129 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_146 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_175 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_192 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_289 );

    SC_METHOD(thread_exitcond_fu_249_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_grp_fu_207_ce);

    SC_METHOD(thread_grp_fu_207_p0);
    sensitive << ( C3_y_load_reg_840 );
    sensitive << ( C3_y_load_5_reg_870 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_grp_fu_207_p1);
    sensitive << ( C3_bias_load_reg_755 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_grp_fu_211_ce);

    SC_METHOD(thread_grp_fu_211_p0);
    sensitive << ( C3_y_load_4_reg_845 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( C3_y_load_6_reg_875 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_grp_fu_211_p1);
    sensitive << ( C3_bias_load_reg_755 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_grp_fu_215_ce);

    SC_METHOD(thread_grp_fu_215_p0);
    sensitive << ( S4_d_q0 );
    sensitive << ( S4_d_load_reg_895 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_64_reg_931 );
    sensitive << ( tmp_69_reg_941 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_grp_fu_215_p1);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( p_0_i_fu_626_p3 );
    sensitive << ( p_0_i6_fu_726_p3 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_grp_fu_220_ce);

    SC_METHOD(thread_grp_fu_220_p0);
    sensitive << ( S4_d_q0 );
    sensitive << ( S4_d_load_reg_895 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_67_reg_936 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( tmp_71_reg_946 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_grp_fu_220_p1);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( p_0_i3_fu_634_p3 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( p_0_i9_fu_734_p3 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_grp_fu_229_opcode);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_229_p0);
    sensitive << ( reg_239 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_229_p1);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_234_opcode);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_234_p0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( reg_244 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_234_p1);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_i_13_fu_255_p2);
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_j_10_fu_524_p2);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_k_9_fu_518_p2);
    sensitive << ( k_reg_196 );

    SC_METHOD(thread_notlhs5_fu_602_p2);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_45_fu_588_p4 );

    SC_METHOD(thread_notlhs7_fu_660_p2);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_50_fu_646_p4 );

    SC_METHOD(thread_notlhs9_fu_702_p2);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_55_fu_688_p4 );

    SC_METHOD(thread_notlhs_fu_560_p2);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_40_fu_546_p4 );

    SC_METHOD(thread_notrhs1_fu_708_p2);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_96_fu_698_p1 );

    SC_METHOD(thread_notrhs6_fu_608_p2);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_94_fu_598_p1 );

    SC_METHOD(thread_notrhs8_fu_666_p2);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_95_fu_656_p1 );

    SC_METHOD(thread_notrhs_fu_566_p2);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_93_fu_556_p1 );

    SC_METHOD(thread_p_0_i3_fu_634_p3);
    sensitive << ( tmp_49_reg_890 );

    SC_METHOD(thread_p_0_i6_fu_726_p3);
    sensitive << ( tmp_54_reg_911 );

    SC_METHOD(thread_p_0_i9_fu_734_p3);
    sensitive << ( tmp_59_reg_916 );

    SC_METHOD(thread_p_0_i_fu_626_p3);
    sensitive << ( tmp_44_reg_885 );

    SC_METHOD(thread_p_shl16_fu_388_p1);
    sensitive << ( tmp_89_fu_380_p3 );

    SC_METHOD(thread_p_shl17_fu_400_p1);
    sensitive << ( tmp_90_fu_392_p3 );

    SC_METHOD(thread_p_shl18_fu_427_p1);
    sensitive << ( tmp_91_fu_419_p3 );

    SC_METHOD(thread_p_shl19_fu_439_p1);
    sensitive << ( tmp_92_fu_431_p3 );

    SC_METHOD(thread_p_shl41_cast_fu_278_p1);
    sensitive << ( tmp_108_fu_270_p3 );

    SC_METHOD(thread_p_shl42_cast_fu_308_p1);
    sensitive << ( tmp_110_fu_300_p3 );

    SC_METHOD(thread_p_shl_cast_fu_296_p1);
    sensitive << ( tmp_109_fu_288_p3 );

    SC_METHOD(thread_p_shl_fu_361_p1);
    sensitive << ( tmp_88_fu_353_p3 );

    SC_METHOD(thread_temp_3_to_int_fu_584_p1);
    sensitive << ( reg_244 );

    SC_METHOD(thread_temp_4_to_int_fu_642_p1);
    sensitive << ( reg_239 );

    SC_METHOD(thread_temp_5_to_int_fu_684_p1);
    sensitive << ( reg_244 );

    SC_METHOD(thread_temp_to_int_fu_542_p1);
    sensitive << ( reg_239 );

    SC_METHOD(thread_tmp_108_fu_270_p3);
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_tmp_109_fu_288_p3);
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_tmp_110_fu_300_p3);
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_tmp_111_fu_538_p1);
    sensitive << ( S4_d_addr15_reg_795 );

    SC_METHOD(thread_tmp_112_fu_483_p1);
    sensitive << ( C3_y_addr11_fu_478_p2 );

    SC_METHOD(thread_tmp_113_fu_503_p1);
    sensitive << ( C3_y_addr12_fu_498_p2 );

    SC_METHOD(thread_tmp_114_fu_530_p1);
    sensitive << ( C3_y_addr10_reg_820 );

    SC_METHOD(thread_tmp_115_fu_534_p1);
    sensitive << ( C3_y_addr4_reg_825 );

    SC_METHOD(thread_tmp_40_fu_546_p4);
    sensitive << ( temp_to_int_fu_542_p1 );

    SC_METHOD(thread_tmp_42_fu_572_p2);
    sensitive << ( notrhs_fu_566_p2 );
    sensitive << ( notlhs_fu_560_p2 );

    SC_METHOD(thread_tmp_44_fu_578_p2);
    sensitive << ( tmp_42_fu_572_p2 );
    sensitive << ( grp_fu_229_p2 );

    SC_METHOD(thread_tmp_45_fu_588_p4);
    sensitive << ( temp_3_to_int_fu_584_p1 );

    SC_METHOD(thread_tmp_47_fu_614_p2);
    sensitive << ( notrhs6_fu_608_p2 );
    sensitive << ( notlhs5_fu_602_p2 );

    SC_METHOD(thread_tmp_49_fu_620_p2);
    sensitive << ( tmp_47_fu_614_p2 );
    sensitive << ( grp_fu_234_p2 );

    SC_METHOD(thread_tmp_50_fu_646_p4);
    sensitive << ( temp_4_to_int_fu_642_p1 );

    SC_METHOD(thread_tmp_52_fu_672_p2);
    sensitive << ( notrhs8_fu_666_p2 );
    sensitive << ( notlhs7_fu_660_p2 );

    SC_METHOD(thread_tmp_54_fu_678_p2);
    sensitive << ( grp_fu_229_p2 );
    sensitive << ( tmp_52_fu_672_p2 );

    SC_METHOD(thread_tmp_55_fu_688_p4);
    sensitive << ( temp_5_to_int_fu_684_p1 );

    SC_METHOD(thread_tmp_57_fu_714_p2);
    sensitive << ( notrhs1_fu_708_p2 );
    sensitive << ( notlhs9_fu_702_p2 );

    SC_METHOD(thread_tmp_59_fu_720_p2);
    sensitive << ( grp_fu_234_p2 );
    sensitive << ( tmp_57_fu_714_p2 );

    SC_METHOD(thread_tmp_61_fu_324_p2);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_62_fu_449_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( k_reg_196 );

    SC_METHOD(thread_tmp_63_fu_455_p4);
    sensitive << ( k_reg_196 );

    SC_METHOD(thread_tmp_66_fu_488_p2);
    sensitive << ( k_reg_196 );

    SC_METHOD(thread_tmp_76_trn_cast_fu_340_p1);
    sensitive << ( tmp_87_fu_330_p4 );

    SC_METHOD(thread_tmp_77_trn_cast_fu_371_p1);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_79_trn6_cast_fu_410_p1);
    sensitive << ( tmp_61_fu_324_p2 );

    SC_METHOD(thread_tmp_82_trn_fu_465_p1);
    sensitive << ( tmp_63_fu_455_p4 );

    SC_METHOD(thread_tmp_83_trn_fu_474_p1);
    sensitive << ( k_reg_196 );

    SC_METHOD(thread_tmp_87_fu_330_p4);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_87_trn_fu_494_p1);
    sensitive << ( tmp_66_fu_488_p2 );

    SC_METHOD(thread_tmp_88_fu_353_p3);
    sensitive << ( S4_d_addr13_fu_344_p2 );

    SC_METHOD(thread_tmp_89_fu_380_p3);
    sensitive << ( C3_y_addr6_fu_375_p2 );

    SC_METHOD(thread_tmp_90_fu_392_p3);
    sensitive << ( C3_y_addr6_fu_375_p2 );

    SC_METHOD(thread_tmp_91_fu_419_p3);
    sensitive << ( C3_y_addr8_fu_414_p2 );

    SC_METHOD(thread_tmp_92_fu_431_p3);
    sensitive << ( C3_y_addr8_fu_414_p2 );

    SC_METHOD(thread_tmp_93_fu_556_p1);
    sensitive << ( temp_to_int_fu_542_p1 );

    SC_METHOD(thread_tmp_94_fu_598_p1);
    sensitive << ( temp_3_to_int_fu_584_p1 );

    SC_METHOD(thread_tmp_95_fu_656_p1);
    sensitive << ( temp_4_to_int_fu_642_p1 );

    SC_METHOD(thread_tmp_96_fu_698_p1);
    sensitive << ( temp_5_to_int_fu_684_p1 );

    SC_METHOD(thread_tmp_fu_261_p1);
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_tmp_s_fu_318_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_trn_cast_fu_266_p1);
    sensitive << ( i_reg_172 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_249_p2 );
    sensitive << ( tmp_s_fu_318_p2 );
    sensitive << ( tmp_62_fu_449_p2 );

    ap_CS_fsm = "000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dateport_DC3_layer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, C3_bias_address0, "(port)C3_bias_address0");
    sc_trace(mVcdFile, C3_bias_ce0, "(port)C3_bias_ce0");
    sc_trace(mVcdFile, C3_bias_q0, "(port)C3_bias_q0");
    sc_trace(mVcdFile, S4_d_address0, "(port)S4_d_address0");
    sc_trace(mVcdFile, S4_d_ce0, "(port)S4_d_ce0");
    sc_trace(mVcdFile, S4_d_q0, "(port)S4_d_q0");
    sc_trace(mVcdFile, C3_y_address0, "(port)C3_y_address0");
    sc_trace(mVcdFile, C3_y_ce0, "(port)C3_y_ce0");
    sc_trace(mVcdFile, C3_y_q0, "(port)C3_y_q0");
    sc_trace(mVcdFile, C3_y_address1, "(port)C3_y_address1");
    sc_trace(mVcdFile, C3_y_ce1, "(port)C3_y_ce1");
    sc_trace(mVcdFile, C3_y_q1, "(port)C3_y_q1");
    sc_trace(mVcdFile, C3_d_address0, "(port)C3_d_address0");
    sc_trace(mVcdFile, C3_d_ce0, "(port)C3_d_ce0");
    sc_trace(mVcdFile, C3_d_we0, "(port)C3_d_we0");
    sc_trace(mVcdFile, C3_d_d0, "(port)C3_d_d0");
    sc_trace(mVcdFile, C3_d_address1, "(port)C3_d_address1");
    sc_trace(mVcdFile, C3_d_ce1, "(port)C3_d_ce1");
    sc_trace(mVcdFile, C3_d_we1, "(port)C3_d_we1");
    sc_trace(mVcdFile, C3_d_d1, "(port)C3_d_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_39, "ap_sig_bdd_39");
    sc_trace(mVcdFile, grp_fu_207_p2, "grp_fu_207_p2");
    sc_trace(mVcdFile, reg_239, "reg_239");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_83, "ap_sig_bdd_83");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_90, "ap_sig_bdd_90");
    sc_trace(mVcdFile, grp_fu_211_p2, "grp_fu_211_p2");
    sc_trace(mVcdFile, reg_244, "reg_244");
    sc_trace(mVcdFile, i_13_fu_255_p2, "i_13_fu_255_p2");
    sc_trace(mVcdFile, i_13_reg_745, "i_13_reg_745");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_102, "ap_sig_bdd_102");
    sc_trace(mVcdFile, exitcond_fu_249_p2, "exitcond_fu_249_p2");
    sc_trace(mVcdFile, C3_bias_load_reg_755, "C3_bias_load_reg_755");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_116, "ap_sig_bdd_116");
    sc_trace(mVcdFile, S4_d_addr12_fu_282_p2, "S4_d_addr12_fu_282_p2");
    sc_trace(mVcdFile, S4_d_addr12_reg_761, "S4_d_addr12_reg_761");
    sc_trace(mVcdFile, C3_y_addr5_fu_312_p2, "C3_y_addr5_fu_312_p2");
    sc_trace(mVcdFile, C3_y_addr5_reg_766, "C3_y_addr5_reg_766");
    sc_trace(mVcdFile, S4_d_addr14_fu_365_p2, "S4_d_addr14_fu_365_p2");
    sc_trace(mVcdFile, S4_d_addr14_reg_775, "S4_d_addr14_reg_775");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_129, "ap_sig_bdd_129");
    sc_trace(mVcdFile, tmp_s_fu_318_p2, "tmp_s_fu_318_p2");
    sc_trace(mVcdFile, C3_y_addr7_fu_404_p2, "C3_y_addr7_fu_404_p2");
    sc_trace(mVcdFile, C3_y_addr7_reg_780, "C3_y_addr7_reg_780");
    sc_trace(mVcdFile, C3_y_addr9_fu_443_p2, "C3_y_addr9_fu_443_p2");
    sc_trace(mVcdFile, C3_y_addr9_reg_786, "C3_y_addr9_reg_786");
    sc_trace(mVcdFile, S4_d_addr15_fu_469_p2, "S4_d_addr15_fu_469_p2");
    sc_trace(mVcdFile, S4_d_addr15_reg_795, "S4_d_addr15_reg_795");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_146, "ap_sig_bdd_146");
    sc_trace(mVcdFile, tmp_62_fu_449_p2, "tmp_62_fu_449_p2");
    sc_trace(mVcdFile, tmp_112_fu_483_p1, "tmp_112_fu_483_p1");
    sc_trace(mVcdFile, tmp_112_reg_800, "tmp_112_reg_800");
    sc_trace(mVcdFile, tmp_113_fu_503_p1, "tmp_113_fu_503_p1");
    sc_trace(mVcdFile, tmp_113_reg_810, "tmp_113_reg_810");
    sc_trace(mVcdFile, C3_y_addr10_fu_508_p2, "C3_y_addr10_fu_508_p2");
    sc_trace(mVcdFile, C3_y_addr10_reg_820, "C3_y_addr10_reg_820");
    sc_trace(mVcdFile, C3_y_addr4_fu_513_p2, "C3_y_addr4_fu_513_p2");
    sc_trace(mVcdFile, C3_y_addr4_reg_825, "C3_y_addr4_reg_825");
    sc_trace(mVcdFile, k_9_fu_518_p2, "k_9_fu_518_p2");
    sc_trace(mVcdFile, k_9_reg_830, "k_9_reg_830");
    sc_trace(mVcdFile, j_10_fu_524_p2, "j_10_fu_524_p2");
    sc_trace(mVcdFile, C3_y_load_reg_840, "C3_y_load_reg_840");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_175, "ap_sig_bdd_175");
    sc_trace(mVcdFile, C3_y_load_4_reg_845, "C3_y_load_4_reg_845");
    sc_trace(mVcdFile, tmp_114_fu_530_p1, "tmp_114_fu_530_p1");
    sc_trace(mVcdFile, tmp_114_reg_850, "tmp_114_reg_850");
    sc_trace(mVcdFile, tmp_115_fu_534_p1, "tmp_115_fu_534_p1");
    sc_trace(mVcdFile, tmp_115_reg_860, "tmp_115_reg_860");
    sc_trace(mVcdFile, C3_y_load_5_reg_870, "C3_y_load_5_reg_870");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_192, "ap_sig_bdd_192");
    sc_trace(mVcdFile, C3_y_load_6_reg_875, "C3_y_load_6_reg_875");
    sc_trace(mVcdFile, tmp_44_fu_578_p2, "tmp_44_fu_578_p2");
    sc_trace(mVcdFile, tmp_44_reg_885, "tmp_44_reg_885");
    sc_trace(mVcdFile, tmp_49_fu_620_p2, "tmp_49_fu_620_p2");
    sc_trace(mVcdFile, tmp_49_reg_890, "tmp_49_reg_890");
    sc_trace(mVcdFile, S4_d_load_reg_895, "S4_d_load_reg_895");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_207, "ap_sig_bdd_207");
    sc_trace(mVcdFile, p_0_i_fu_626_p3, "p_0_i_fu_626_p3");
    sc_trace(mVcdFile, p_0_i3_fu_634_p3, "p_0_i3_fu_634_p3");
    sc_trace(mVcdFile, tmp_54_fu_678_p2, "tmp_54_fu_678_p2");
    sc_trace(mVcdFile, tmp_54_reg_911, "tmp_54_reg_911");
    sc_trace(mVcdFile, tmp_59_fu_720_p2, "tmp_59_fu_720_p2");
    sc_trace(mVcdFile, tmp_59_reg_916, "tmp_59_reg_916");
    sc_trace(mVcdFile, p_0_i6_fu_726_p3, "p_0_i6_fu_726_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_224, "ap_sig_bdd_224");
    sc_trace(mVcdFile, p_0_i9_fu_734_p3, "p_0_i9_fu_734_p3");
    sc_trace(mVcdFile, grp_fu_215_p2, "grp_fu_215_p2");
    sc_trace(mVcdFile, tmp_64_reg_931, "tmp_64_reg_931");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_bdd_235, "ap_sig_bdd_235");
    sc_trace(mVcdFile, grp_fu_220_p2, "grp_fu_220_p2");
    sc_trace(mVcdFile, tmp_67_reg_936, "tmp_67_reg_936");
    sc_trace(mVcdFile, tmp_69_reg_941, "tmp_69_reg_941");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_245, "ap_sig_bdd_245");
    sc_trace(mVcdFile, tmp_71_reg_946, "tmp_71_reg_946");
    sc_trace(mVcdFile, i_reg_172, "i_reg_172");
    sc_trace(mVcdFile, j_reg_184, "j_reg_184");
    sc_trace(mVcdFile, k_reg_196, "k_reg_196");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_bdd_265, "ap_sig_bdd_265");
    sc_trace(mVcdFile, tmp_fu_261_p1, "tmp_fu_261_p1");
    sc_trace(mVcdFile, tmp_111_fu_538_p1, "tmp_111_fu_538_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_275, "ap_sig_bdd_275");
    sc_trace(mVcdFile, grp_fu_207_p0, "grp_fu_207_p0");
    sc_trace(mVcdFile, grp_fu_207_p1, "grp_fu_207_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_289, "ap_sig_bdd_289");
    sc_trace(mVcdFile, grp_fu_211_p0, "grp_fu_211_p0");
    sc_trace(mVcdFile, grp_fu_211_p1, "grp_fu_211_p1");
    sc_trace(mVcdFile, grp_fu_215_p0, "grp_fu_215_p0");
    sc_trace(mVcdFile, grp_fu_215_p1, "grp_fu_215_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_302, "ap_sig_bdd_302");
    sc_trace(mVcdFile, grp_fu_220_p0, "grp_fu_220_p0");
    sc_trace(mVcdFile, grp_fu_220_p1, "grp_fu_220_p1");
    sc_trace(mVcdFile, grp_fu_229_p0, "grp_fu_229_p0");
    sc_trace(mVcdFile, grp_fu_229_p1, "grp_fu_229_p1");
    sc_trace(mVcdFile, grp_fu_234_p0, "grp_fu_234_p0");
    sc_trace(mVcdFile, grp_fu_234_p1, "grp_fu_234_p1");
    sc_trace(mVcdFile, tmp_108_fu_270_p3, "tmp_108_fu_270_p3");
    sc_trace(mVcdFile, tmp_trn_cast_fu_266_p1, "tmp_trn_cast_fu_266_p1");
    sc_trace(mVcdFile, p_shl41_cast_fu_278_p1, "p_shl41_cast_fu_278_p1");
    sc_trace(mVcdFile, tmp_109_fu_288_p3, "tmp_109_fu_288_p3");
    sc_trace(mVcdFile, tmp_110_fu_300_p3, "tmp_110_fu_300_p3");
    sc_trace(mVcdFile, p_shl42_cast_fu_308_p1, "p_shl42_cast_fu_308_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_296_p1, "p_shl_cast_fu_296_p1");
    sc_trace(mVcdFile, tmp_87_fu_330_p4, "tmp_87_fu_330_p4");
    sc_trace(mVcdFile, tmp_76_trn_cast_fu_340_p1, "tmp_76_trn_cast_fu_340_p1");
    sc_trace(mVcdFile, S4_d_addr13_fu_344_p2, "S4_d_addr13_fu_344_p2");
    sc_trace(mVcdFile, tmp_88_fu_353_p3, "tmp_88_fu_353_p3");
    sc_trace(mVcdFile, p_shl_fu_361_p1, "p_shl_fu_361_p1");
    sc_trace(mVcdFile, S4_d_addr13_cast_fu_349_p1, "S4_d_addr13_cast_fu_349_p1");
    sc_trace(mVcdFile, tmp_77_trn_cast_fu_371_p1, "tmp_77_trn_cast_fu_371_p1");
    sc_trace(mVcdFile, C3_y_addr6_fu_375_p2, "C3_y_addr6_fu_375_p2");
    sc_trace(mVcdFile, tmp_89_fu_380_p3, "tmp_89_fu_380_p3");
    sc_trace(mVcdFile, tmp_90_fu_392_p3, "tmp_90_fu_392_p3");
    sc_trace(mVcdFile, p_shl16_fu_388_p1, "p_shl16_fu_388_p1");
    sc_trace(mVcdFile, p_shl17_fu_400_p1, "p_shl17_fu_400_p1");
    sc_trace(mVcdFile, tmp_61_fu_324_p2, "tmp_61_fu_324_p2");
    sc_trace(mVcdFile, tmp_79_trn6_cast_fu_410_p1, "tmp_79_trn6_cast_fu_410_p1");
    sc_trace(mVcdFile, C3_y_addr8_fu_414_p2, "C3_y_addr8_fu_414_p2");
    sc_trace(mVcdFile, tmp_91_fu_419_p3, "tmp_91_fu_419_p3");
    sc_trace(mVcdFile, tmp_92_fu_431_p3, "tmp_92_fu_431_p3");
    sc_trace(mVcdFile, p_shl18_fu_427_p1, "p_shl18_fu_427_p1");
    sc_trace(mVcdFile, p_shl19_fu_439_p1, "p_shl19_fu_439_p1");
    sc_trace(mVcdFile, tmp_63_fu_455_p4, "tmp_63_fu_455_p4");
    sc_trace(mVcdFile, tmp_82_trn_fu_465_p1, "tmp_82_trn_fu_465_p1");
    sc_trace(mVcdFile, tmp_83_trn_fu_474_p1, "tmp_83_trn_fu_474_p1");
    sc_trace(mVcdFile, C3_y_addr11_fu_478_p2, "C3_y_addr11_fu_478_p2");
    sc_trace(mVcdFile, tmp_66_fu_488_p2, "tmp_66_fu_488_p2");
    sc_trace(mVcdFile, tmp_87_trn_fu_494_p1, "tmp_87_trn_fu_494_p1");
    sc_trace(mVcdFile, C3_y_addr12_fu_498_p2, "C3_y_addr12_fu_498_p2");
    sc_trace(mVcdFile, temp_to_int_fu_542_p1, "temp_to_int_fu_542_p1");
    sc_trace(mVcdFile, tmp_40_fu_546_p4, "tmp_40_fu_546_p4");
    sc_trace(mVcdFile, tmp_93_fu_556_p1, "tmp_93_fu_556_p1");
    sc_trace(mVcdFile, notrhs_fu_566_p2, "notrhs_fu_566_p2");
    sc_trace(mVcdFile, notlhs_fu_560_p2, "notlhs_fu_560_p2");
    sc_trace(mVcdFile, tmp_42_fu_572_p2, "tmp_42_fu_572_p2");
    sc_trace(mVcdFile, grp_fu_229_p2, "grp_fu_229_p2");
    sc_trace(mVcdFile, temp_3_to_int_fu_584_p1, "temp_3_to_int_fu_584_p1");
    sc_trace(mVcdFile, tmp_45_fu_588_p4, "tmp_45_fu_588_p4");
    sc_trace(mVcdFile, tmp_94_fu_598_p1, "tmp_94_fu_598_p1");
    sc_trace(mVcdFile, notrhs6_fu_608_p2, "notrhs6_fu_608_p2");
    sc_trace(mVcdFile, notlhs5_fu_602_p2, "notlhs5_fu_602_p2");
    sc_trace(mVcdFile, tmp_47_fu_614_p2, "tmp_47_fu_614_p2");
    sc_trace(mVcdFile, grp_fu_234_p2, "grp_fu_234_p2");
    sc_trace(mVcdFile, temp_4_to_int_fu_642_p1, "temp_4_to_int_fu_642_p1");
    sc_trace(mVcdFile, tmp_50_fu_646_p4, "tmp_50_fu_646_p4");
    sc_trace(mVcdFile, tmp_95_fu_656_p1, "tmp_95_fu_656_p1");
    sc_trace(mVcdFile, notrhs8_fu_666_p2, "notrhs8_fu_666_p2");
    sc_trace(mVcdFile, notlhs7_fu_660_p2, "notlhs7_fu_660_p2");
    sc_trace(mVcdFile, tmp_52_fu_672_p2, "tmp_52_fu_672_p2");
    sc_trace(mVcdFile, temp_5_to_int_fu_684_p1, "temp_5_to_int_fu_684_p1");
    sc_trace(mVcdFile, tmp_55_fu_688_p4, "tmp_55_fu_688_p4");
    sc_trace(mVcdFile, tmp_96_fu_698_p1, "tmp_96_fu_698_p1");
    sc_trace(mVcdFile, notrhs1_fu_708_p2, "notrhs1_fu_708_p2");
    sc_trace(mVcdFile, notlhs9_fu_702_p2, "notlhs9_fu_702_p2");
    sc_trace(mVcdFile, tmp_57_fu_714_p2, "tmp_57_fu_714_p2");
    sc_trace(mVcdFile, grp_fu_207_ce, "grp_fu_207_ce");
    sc_trace(mVcdFile, grp_fu_211_ce, "grp_fu_211_ce");
    sc_trace(mVcdFile, grp_fu_215_ce, "grp_fu_215_ce");
    sc_trace(mVcdFile, grp_fu_220_ce, "grp_fu_220_ce");
    sc_trace(mVcdFile, grp_fu_229_opcode, "grp_fu_229_opcode");
    sc_trace(mVcdFile, grp_fu_234_opcode, "grp_fu_234_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dateport_DC3_layer::~dateport_DC3_layer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dateport_fadd_32ns_32ns_32_5_full_dsp_U54;
    delete dateport_fadd_32ns_32ns_32_5_full_dsp_U55;
    delete dateport_fmul_32ns_32ns_32_4_max_dsp_U56;
    delete dateport_fmul_32ns_32ns_32_4_max_dsp_U57;
    delete dateport_fcmp_32ns_32ns_1_1_U58;
    delete dateport_fcmp_32ns_32ns_1_1_U59;
}

void dateport_DC3_layer::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_318_p2.read()))) {
        i_reg_172 = i_13_reg_745.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_172 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        j_reg_184 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_62_fu_449_p2.read()))) {
        j_reg_184 = j_10_fu_524_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_318_p2.read()))) {
        k_reg_196 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        k_reg_196 = k_9_reg_830.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        C3_bias_load_reg_755 = C3_bias_q0.read();
        C3_y_addr5_reg_766 = C3_y_addr5_fu_312_p2.read();
        S4_d_addr12_reg_761 = S4_d_addr12_fu_282_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_62_fu_449_p2.read()))) {
        C3_y_addr10_reg_820 = C3_y_addr10_fu_508_p2.read();
        C3_y_addr4_reg_825 = C3_y_addr4_fu_513_p2.read();
        S4_d_addr15_reg_795 = S4_d_addr15_fu_469_p2.read();
        k_9_reg_830 = k_9_fu_518_p2.read();
        tmp_112_reg_800 = tmp_112_fu_483_p1.read();
        tmp_113_reg_810 = tmp_113_fu_503_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_318_p2.read()))) {
        C3_y_addr7_reg_780 = C3_y_addr7_fu_404_p2.read();
        C3_y_addr9_reg_786 = C3_y_addr9_fu_443_p2.read();
        S4_d_addr14_reg_775 = S4_d_addr14_fu_365_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        C3_y_load_4_reg_845 = C3_y_q1.read();
        C3_y_load_reg_840 = C3_y_q0.read();
        tmp_114_reg_850 = tmp_114_fu_530_p1.read();
        tmp_115_reg_860 = tmp_115_fu_534_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        C3_y_load_5_reg_870 = C3_y_q0.read();
        C3_y_load_6_reg_875 = C3_y_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        S4_d_load_reg_895 = S4_d_q0.read();
        tmp_54_reg_911 = tmp_54_fu_678_p2.read();
        tmp_59_reg_916 = tmp_59_fu_720_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_13_reg_745 = i_13_fu_255_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        reg_239 = grp_fu_207_p2.read();
        reg_244 = grp_fu_211_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        tmp_44_reg_885 = tmp_44_fu_578_p2.read();
        tmp_49_reg_890 = tmp_49_fu_620_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        tmp_64_reg_931 = grp_fu_215_p2.read();
        tmp_67_reg_936 = grp_fu_220_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        tmp_69_reg_941 = grp_fu_215_p2.read();
        tmp_71_reg_946 = grp_fu_220_p2.read();
    }
}

void dateport_DC3_layer::thread_C3_bias_address0() {
    C3_bias_address0 =  (sc_lv<4>) (tmp_fu_261_p1.read());
}

void dateport_DC3_layer::thread_C3_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        C3_bias_ce0 = ap_const_logic_1;
    } else {
        C3_bias_ce0 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_C3_d_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        C3_d_address0 =  (sc_lv<11>) (tmp_114_reg_850.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        C3_d_address0 =  (sc_lv<11>) (tmp_112_reg_800.read());
    } else {
        C3_d_address0 = "XXXXXXXXXXX";
    }
}

void dateport_DC3_layer::thread_C3_d_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        C3_d_address1 =  (sc_lv<11>) (tmp_115_reg_860.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        C3_d_address1 =  (sc_lv<11>) (tmp_113_reg_810.read());
    } else {
        C3_d_address1 = "XXXXXXXXXXX";
    }
}

void dateport_DC3_layer::thread_C3_d_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        C3_d_ce0 = ap_const_logic_1;
    } else {
        C3_d_ce0 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_C3_d_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        C3_d_ce1 = ap_const_logic_1;
    } else {
        C3_d_ce1 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_C3_d_d0() {
    C3_d_d0 = grp_fu_215_p2.read();
}

void dateport_DC3_layer::thread_C3_d_d1() {
    C3_d_d1 = grp_fu_220_p2.read();
}

void dateport_DC3_layer::thread_C3_d_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        C3_d_we0 = ap_const_logic_1;
    } else {
        C3_d_we0 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_C3_d_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        C3_d_we1 = ap_const_logic_1;
    } else {
        C3_d_we1 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_C3_y_addr10_fu_508_p2() {
    C3_y_addr10_fu_508_p2 = (!tmp_83_trn_fu_474_p1.read().is_01() || !C3_y_addr9_reg_786.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_83_trn_fu_474_p1.read()) + sc_biguint<32>(C3_y_addr9_reg_786.read()));
}

void dateport_DC3_layer::thread_C3_y_addr11_fu_478_p2() {
    C3_y_addr11_fu_478_p2 = (!tmp_83_trn_fu_474_p1.read().is_01() || !C3_y_addr7_reg_780.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_83_trn_fu_474_p1.read()) + sc_biguint<32>(C3_y_addr7_reg_780.read()));
}

void dateport_DC3_layer::thread_C3_y_addr12_fu_498_p2() {
    C3_y_addr12_fu_498_p2 = (!tmp_87_trn_fu_494_p1.read().is_01() || !C3_y_addr7_reg_780.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_87_trn_fu_494_p1.read()) + sc_biguint<32>(C3_y_addr7_reg_780.read()));
}

void dateport_DC3_layer::thread_C3_y_addr4_fu_513_p2() {
    C3_y_addr4_fu_513_p2 = (!tmp_87_trn_fu_494_p1.read().is_01() || !C3_y_addr9_reg_786.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_87_trn_fu_494_p1.read()) + sc_biguint<32>(C3_y_addr9_reg_786.read()));
}

void dateport_DC3_layer::thread_C3_y_addr5_fu_312_p2() {
    C3_y_addr5_fu_312_p2 = (!p_shl42_cast_fu_308_p1.read().is_01() || !p_shl_cast_fu_296_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl42_cast_fu_308_p1.read()) + sc_biguint<9>(p_shl_cast_fu_296_p1.read()));
}

void dateport_DC3_layer::thread_C3_y_addr6_fu_375_p2() {
    C3_y_addr6_fu_375_p2 = (!tmp_77_trn_cast_fu_371_p1.read().is_01() || !C3_y_addr5_reg_766.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_77_trn_cast_fu_371_p1.read()) + sc_biguint<9>(C3_y_addr5_reg_766.read()));
}

void dateport_DC3_layer::thread_C3_y_addr7_fu_404_p2() {
    C3_y_addr7_fu_404_p2 = (!p_shl16_fu_388_p1.read().is_01() || !p_shl17_fu_400_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_shl16_fu_388_p1.read()) + sc_biguint<32>(p_shl17_fu_400_p1.read()));
}

void dateport_DC3_layer::thread_C3_y_addr8_fu_414_p2() {
    C3_y_addr8_fu_414_p2 = (!tmp_79_trn6_cast_fu_410_p1.read().is_01() || !C3_y_addr5_reg_766.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_79_trn6_cast_fu_410_p1.read()) + sc_biguint<9>(C3_y_addr5_reg_766.read()));
}

void dateport_DC3_layer::thread_C3_y_addr9_fu_443_p2() {
    C3_y_addr9_fu_443_p2 = (!p_shl18_fu_427_p1.read().is_01() || !p_shl19_fu_439_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_shl18_fu_427_p1.read()) + sc_biguint<32>(p_shl19_fu_439_p1.read()));
}

void dateport_DC3_layer::thread_C3_y_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        C3_y_address0 =  (sc_lv<11>) (tmp_114_fu_530_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        C3_y_address0 =  (sc_lv<11>) (tmp_112_fu_483_p1.read());
    } else {
        C3_y_address0 = "XXXXXXXXXXX";
    }
}

void dateport_DC3_layer::thread_C3_y_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        C3_y_address1 =  (sc_lv<11>) (tmp_115_fu_534_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        C3_y_address1 =  (sc_lv<11>) (tmp_113_fu_503_p1.read());
    } else {
        C3_y_address1 = "XXXXXXXXXXX";
    }
}

void dateport_DC3_layer::thread_C3_y_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        C3_y_ce0 = ap_const_logic_1;
    } else {
        C3_y_ce0 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_C3_y_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        C3_y_ce1 = ap_const_logic_1;
    } else {
        C3_y_ce1 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_S4_d_addr12_fu_282_p2() {
    S4_d_addr12_fu_282_p2 = (!tmp_trn_cast_fu_266_p1.read().is_01() || !p_shl41_cast_fu_278_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_trn_cast_fu_266_p1.read()) + sc_biguint<8>(p_shl41_cast_fu_278_p1.read()));
}

void dateport_DC3_layer::thread_S4_d_addr13_cast_fu_349_p1() {
    S4_d_addr13_cast_fu_349_p1 = esl_zext<32,8>(S4_d_addr13_fu_344_p2.read());
}

void dateport_DC3_layer::thread_S4_d_addr13_fu_344_p2() {
    S4_d_addr13_fu_344_p2 = (!tmp_76_trn_cast_fu_340_p1.read().is_01() || !S4_d_addr12_reg_761.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_76_trn_cast_fu_340_p1.read()) + sc_biguint<8>(S4_d_addr12_reg_761.read()));
}

void dateport_DC3_layer::thread_S4_d_addr14_fu_365_p2() {
    S4_d_addr14_fu_365_p2 = (!p_shl_fu_361_p1.read().is_01() || !S4_d_addr13_cast_fu_349_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_shl_fu_361_p1.read()) + sc_biguint<32>(S4_d_addr13_cast_fu_349_p1.read()));
}

void dateport_DC3_layer::thread_S4_d_addr15_fu_469_p2() {
    S4_d_addr15_fu_469_p2 = (!tmp_82_trn_fu_465_p1.read().is_01() || !S4_d_addr14_reg_775.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_82_trn_fu_465_p1.read()) + sc_biguint<32>(S4_d_addr14_reg_775.read()));
}

void dateport_DC3_layer::thread_S4_d_address0() {
    S4_d_address0 =  (sc_lv<9>) (tmp_111_fu_538_p1.read());
}

void dateport_DC3_layer::thread_S4_d_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        S4_d_ce0 = ap_const_logic_1;
    } else {
        S4_d_ce0 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_249_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond_fu_249_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_bdd_102() {
    ap_sig_bdd_102 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dateport_DC3_layer::thread_ap_sig_bdd_116() {
    ap_sig_bdd_116 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dateport_DC3_layer::thread_ap_sig_bdd_129() {
    ap_sig_bdd_129 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dateport_DC3_layer::thread_ap_sig_bdd_146() {
    ap_sig_bdd_146 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dateport_DC3_layer::thread_ap_sig_bdd_175() {
    ap_sig_bdd_175 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dateport_DC3_layer::thread_ap_sig_bdd_192() {
    ap_sig_bdd_192 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dateport_DC3_layer::thread_ap_sig_bdd_207() {
    ap_sig_bdd_207 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void dateport_DC3_layer::thread_ap_sig_bdd_224() {
    ap_sig_bdd_224 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void dateport_DC3_layer::thread_ap_sig_bdd_235() {
    ap_sig_bdd_235 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void dateport_DC3_layer::thread_ap_sig_bdd_245() {
    ap_sig_bdd_245 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void dateport_DC3_layer::thread_ap_sig_bdd_265() {
    ap_sig_bdd_265 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void dateport_DC3_layer::thread_ap_sig_bdd_275() {
    ap_sig_bdd_275 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void dateport_DC3_layer::thread_ap_sig_bdd_289() {
    ap_sig_bdd_289 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dateport_DC3_layer::thread_ap_sig_bdd_302() {
    ap_sig_bdd_302 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void dateport_DC3_layer::thread_ap_sig_bdd_39() {
    ap_sig_bdd_39 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dateport_DC3_layer::thread_ap_sig_bdd_83() {
    ap_sig_bdd_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dateport_DC3_layer::thread_ap_sig_bdd_90() {
    ap_sig_bdd_90 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_83.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_90.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_207.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_224.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_bdd_235.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_245.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_302.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_39.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_275.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_bdd_265.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_102.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_116.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_129.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_146.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_175.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_192.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_289.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dateport_DC3_layer::thread_exitcond_fu_249_p2() {
    exitcond_fu_249_p2 = (!i_reg_172.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_172.read() == ap_const_lv5_10);
}

void dateport_DC3_layer::thread_grp_fu_207_ce() {
    grp_fu_207_ce = ap_const_logic_1;
}

void dateport_DC3_layer::thread_grp_fu_207_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        grp_fu_207_p0 = C3_y_load_5_reg_870.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        grp_fu_207_p0 = C3_y_load_reg_840.read();
    } else {
        grp_fu_207_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dateport_DC3_layer::thread_grp_fu_207_p1() {
    grp_fu_207_p1 = C3_bias_load_reg_755.read();
}

void dateport_DC3_layer::thread_grp_fu_211_ce() {
    grp_fu_211_ce = ap_const_logic_1;
}

void dateport_DC3_layer::thread_grp_fu_211_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        grp_fu_211_p0 = C3_y_load_6_reg_875.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        grp_fu_211_p0 = C3_y_load_4_reg_845.read();
    } else {
        grp_fu_211_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dateport_DC3_layer::thread_grp_fu_211_p1() {
    grp_fu_211_p1 = C3_bias_load_reg_755.read();
}

void dateport_DC3_layer::thread_grp_fu_215_ce() {
    grp_fu_215_ce = ap_const_logic_1;
}

void dateport_DC3_layer::thread_grp_fu_215_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        grp_fu_215_p0 = tmp_69_reg_941.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        grp_fu_215_p0 = tmp_64_reg_931.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        grp_fu_215_p0 = S4_d_load_reg_895.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_215_p0 = S4_d_q0.read();
    } else {
        grp_fu_215_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dateport_DC3_layer::thread_grp_fu_215_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        grp_fu_215_p1 = ap_const_lv32_3E800000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        grp_fu_215_p1 = p_0_i6_fu_726_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_215_p1 = p_0_i_fu_626_p3.read();
    } else {
        grp_fu_215_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dateport_DC3_layer::thread_grp_fu_220_ce() {
    grp_fu_220_ce = ap_const_logic_1;
}

void dateport_DC3_layer::thread_grp_fu_220_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        grp_fu_220_p0 = tmp_71_reg_946.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        grp_fu_220_p0 = tmp_67_reg_936.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        grp_fu_220_p0 = S4_d_load_reg_895.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_220_p0 = S4_d_q0.read();
    } else {
        grp_fu_220_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dateport_DC3_layer::thread_grp_fu_220_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        grp_fu_220_p1 = ap_const_lv32_3E800000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        grp_fu_220_p1 = p_0_i9_fu_734_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_220_p1 = p_0_i3_fu_634_p3.read();
    } else {
        grp_fu_220_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dateport_DC3_layer::thread_grp_fu_229_opcode() {
    grp_fu_229_opcode = ap_const_lv5_2;
}

void dateport_DC3_layer::thread_grp_fu_229_p0() {
    grp_fu_229_p0 = reg_239.read();
}

void dateport_DC3_layer::thread_grp_fu_229_p1() {
    grp_fu_229_p1 = ap_const_lv32_0;
}

void dateport_DC3_layer::thread_grp_fu_234_opcode() {
    grp_fu_234_opcode = ap_const_lv5_2;
}

void dateport_DC3_layer::thread_grp_fu_234_p0() {
    grp_fu_234_p0 = reg_244.read();
}

void dateport_DC3_layer::thread_grp_fu_234_p1() {
    grp_fu_234_p1 = ap_const_lv32_0;
}

void dateport_DC3_layer::thread_i_13_fu_255_p2() {
    i_13_fu_255_p2 = (!i_reg_172.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_172.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dateport_DC3_layer::thread_j_10_fu_524_p2() {
    j_10_fu_524_p2 = (!j_reg_184.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_184.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void dateport_DC3_layer::thread_k_9_fu_518_p2() {
    k_9_fu_518_p2 = (!ap_const_lv4_2.is_01() || !k_reg_196.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_2) + sc_biguint<4>(k_reg_196.read()));
}

void dateport_DC3_layer::thread_notlhs5_fu_602_p2() {
    notlhs5_fu_602_p2 = (!tmp_45_fu_588_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_45_fu_588_p4.read() != ap_const_lv8_FF);
}

void dateport_DC3_layer::thread_notlhs7_fu_660_p2() {
    notlhs7_fu_660_p2 = (!tmp_50_fu_646_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_50_fu_646_p4.read() != ap_const_lv8_FF);
}

void dateport_DC3_layer::thread_notlhs9_fu_702_p2() {
    notlhs9_fu_702_p2 = (!tmp_55_fu_688_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_55_fu_688_p4.read() != ap_const_lv8_FF);
}

void dateport_DC3_layer::thread_notlhs_fu_560_p2() {
    notlhs_fu_560_p2 = (!tmp_40_fu_546_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_40_fu_546_p4.read() != ap_const_lv8_FF);
}

void dateport_DC3_layer::thread_notrhs1_fu_708_p2() {
    notrhs1_fu_708_p2 = (!tmp_96_fu_698_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_96_fu_698_p1.read() == ap_const_lv23_0);
}

void dateport_DC3_layer::thread_notrhs6_fu_608_p2() {
    notrhs6_fu_608_p2 = (!tmp_94_fu_598_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_94_fu_598_p1.read() == ap_const_lv23_0);
}

void dateport_DC3_layer::thread_notrhs8_fu_666_p2() {
    notrhs8_fu_666_p2 = (!tmp_95_fu_656_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_95_fu_656_p1.read() == ap_const_lv23_0);
}

void dateport_DC3_layer::thread_notrhs_fu_566_p2() {
    notrhs_fu_566_p2 = (!tmp_93_fu_556_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_93_fu_556_p1.read() == ap_const_lv23_0);
}

void dateport_DC3_layer::thread_p_0_i3_fu_634_p3() {
    p_0_i3_fu_634_p3 = (!tmp_49_reg_890.read()[0].is_01())? sc_lv<32>(): ((tmp_49_reg_890.read()[0].to_bool())? ap_const_lv32_3F800000: ap_const_lv32_0);
}

void dateport_DC3_layer::thread_p_0_i6_fu_726_p3() {
    p_0_i6_fu_726_p3 = (!tmp_54_reg_911.read()[0].is_01())? sc_lv<32>(): ((tmp_54_reg_911.read()[0].to_bool())? ap_const_lv32_3F800000: ap_const_lv32_0);
}

void dateport_DC3_layer::thread_p_0_i9_fu_734_p3() {
    p_0_i9_fu_734_p3 = (!tmp_59_reg_916.read()[0].is_01())? sc_lv<32>(): ((tmp_59_reg_916.read()[0].to_bool())? ap_const_lv32_3F800000: ap_const_lv32_0);
}

void dateport_DC3_layer::thread_p_0_i_fu_626_p3() {
    p_0_i_fu_626_p3 = (!tmp_44_reg_885.read()[0].is_01())? sc_lv<32>(): ((tmp_44_reg_885.read()[0].to_bool())? ap_const_lv32_3F800000: ap_const_lv32_0);
}

void dateport_DC3_layer::thread_p_shl16_fu_388_p1() {
    p_shl16_fu_388_p1 = esl_zext<32,12>(tmp_89_fu_380_p3.read());
}

void dateport_DC3_layer::thread_p_shl17_fu_400_p1() {
    p_shl17_fu_400_p1 = esl_zext<32,10>(tmp_90_fu_392_p3.read());
}

void dateport_DC3_layer::thread_p_shl18_fu_427_p1() {
    p_shl18_fu_427_p1 = esl_zext<32,12>(tmp_91_fu_419_p3.read());
}

void dateport_DC3_layer::thread_p_shl19_fu_439_p1() {
    p_shl19_fu_439_p1 = esl_zext<32,10>(tmp_92_fu_431_p3.read());
}

void dateport_DC3_layer::thread_p_shl41_cast_fu_278_p1() {
    p_shl41_cast_fu_278_p1 = esl_zext<8,7>(tmp_108_fu_270_p3.read());
}

void dateport_DC3_layer::thread_p_shl42_cast_fu_308_p1() {
    p_shl42_cast_fu_308_p1 = esl_zext<9,6>(tmp_110_fu_300_p3.read());
}

void dateport_DC3_layer::thread_p_shl_cast_fu_296_p1() {
    p_shl_cast_fu_296_p1 = esl_zext<9,8>(tmp_109_fu_288_p3.read());
}

void dateport_DC3_layer::thread_p_shl_fu_361_p1() {
    p_shl_fu_361_p1 = esl_zext<32,10>(tmp_88_fu_353_p3.read());
}

void dateport_DC3_layer::thread_temp_3_to_int_fu_584_p1() {
    temp_3_to_int_fu_584_p1 = reg_244.read();
}

void dateport_DC3_layer::thread_temp_4_to_int_fu_642_p1() {
    temp_4_to_int_fu_642_p1 = reg_239.read();
}

void dateport_DC3_layer::thread_temp_5_to_int_fu_684_p1() {
    temp_5_to_int_fu_684_p1 = reg_244.read();
}

void dateport_DC3_layer::thread_temp_to_int_fu_542_p1() {
    temp_to_int_fu_542_p1 = reg_239.read();
}

void dateport_DC3_layer::thread_tmp_108_fu_270_p3() {
    tmp_108_fu_270_p3 = esl_concat<5,2>(i_reg_172.read(), ap_const_lv2_0);
}

void dateport_DC3_layer::thread_tmp_109_fu_288_p3() {
    tmp_109_fu_288_p3 = esl_concat<5,3>(i_reg_172.read(), ap_const_lv3_0);
}

void dateport_DC3_layer::thread_tmp_110_fu_300_p3() {
    tmp_110_fu_300_p3 = esl_concat<5,1>(i_reg_172.read(), ap_const_lv1_0);
}

void dateport_DC3_layer::thread_tmp_111_fu_538_p1() {
    tmp_111_fu_538_p1 = esl_zext<64,32>(S4_d_addr15_reg_795.read());
}

void dateport_DC3_layer::thread_tmp_112_fu_483_p1() {
    tmp_112_fu_483_p1 = esl_zext<64,32>(C3_y_addr11_fu_478_p2.read());
}

void dateport_DC3_layer::thread_tmp_113_fu_503_p1() {
    tmp_113_fu_503_p1 = esl_zext<64,32>(C3_y_addr12_fu_498_p2.read());
}

void dateport_DC3_layer::thread_tmp_114_fu_530_p1() {
    tmp_114_fu_530_p1 = esl_zext<64,32>(C3_y_addr10_reg_820.read());
}

void dateport_DC3_layer::thread_tmp_115_fu_534_p1() {
    tmp_115_fu_534_p1 = esl_zext<64,32>(C3_y_addr4_reg_825.read());
}

void dateport_DC3_layer::thread_tmp_40_fu_546_p4() {
    tmp_40_fu_546_p4 = temp_to_int_fu_542_p1.read().range(30, 23);
}

void dateport_DC3_layer::thread_tmp_42_fu_572_p2() {
    tmp_42_fu_572_p2 = (notrhs_fu_566_p2.read() | notlhs_fu_560_p2.read());
}

void dateport_DC3_layer::thread_tmp_44_fu_578_p2() {
    tmp_44_fu_578_p2 = (tmp_42_fu_572_p2.read() & grp_fu_229_p2.read());
}

void dateport_DC3_layer::thread_tmp_45_fu_588_p4() {
    tmp_45_fu_588_p4 = temp_3_to_int_fu_584_p1.read().range(30, 23);
}

void dateport_DC3_layer::thread_tmp_47_fu_614_p2() {
    tmp_47_fu_614_p2 = (notrhs6_fu_608_p2.read() | notlhs5_fu_602_p2.read());
}

void dateport_DC3_layer::thread_tmp_49_fu_620_p2() {
    tmp_49_fu_620_p2 = (tmp_47_fu_614_p2.read() & grp_fu_234_p2.read());
}

void dateport_DC3_layer::thread_tmp_50_fu_646_p4() {
    tmp_50_fu_646_p4 = temp_4_to_int_fu_642_p1.read().range(30, 23);
}

void dateport_DC3_layer::thread_tmp_52_fu_672_p2() {
    tmp_52_fu_672_p2 = (notrhs8_fu_666_p2.read() | notlhs7_fu_660_p2.read());
}

void dateport_DC3_layer::thread_tmp_54_fu_678_p2() {
    tmp_54_fu_678_p2 = (tmp_52_fu_672_p2.read() & grp_fu_229_p2.read());
}

void dateport_DC3_layer::thread_tmp_55_fu_688_p4() {
    tmp_55_fu_688_p4 = temp_5_to_int_fu_684_p1.read().range(30, 23);
}

void dateport_DC3_layer::thread_tmp_57_fu_714_p2() {
    tmp_57_fu_714_p2 = (notrhs1_fu_708_p2.read() | notlhs9_fu_702_p2.read());
}

void dateport_DC3_layer::thread_tmp_59_fu_720_p2() {
    tmp_59_fu_720_p2 = (tmp_57_fu_714_p2.read() & grp_fu_234_p2.read());
}

void dateport_DC3_layer::thread_tmp_61_fu_324_p2() {
    tmp_61_fu_324_p2 = (j_reg_184.read() | ap_const_lv4_1);
}

void dateport_DC3_layer::thread_tmp_62_fu_449_p2() {
    tmp_62_fu_449_p2 = (!k_reg_196.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): (sc_biguint<4>(k_reg_196.read()) < sc_biguint<4>(ap_const_lv4_A));
}

void dateport_DC3_layer::thread_tmp_63_fu_455_p4() {
    tmp_63_fu_455_p4 = k_reg_196.read().range(3, 1);
}

void dateport_DC3_layer::thread_tmp_66_fu_488_p2() {
    tmp_66_fu_488_p2 = (k_reg_196.read() | ap_const_lv4_1);
}

void dateport_DC3_layer::thread_tmp_76_trn_cast_fu_340_p1() {
    tmp_76_trn_cast_fu_340_p1 = esl_zext<8,3>(tmp_87_fu_330_p4.read());
}

void dateport_DC3_layer::thread_tmp_77_trn_cast_fu_371_p1() {
    tmp_77_trn_cast_fu_371_p1 = esl_zext<9,4>(j_reg_184.read());
}

void dateport_DC3_layer::thread_tmp_79_trn6_cast_fu_410_p1() {
    tmp_79_trn6_cast_fu_410_p1 = esl_zext<9,4>(tmp_61_fu_324_p2.read());
}

void dateport_DC3_layer::thread_tmp_82_trn_fu_465_p1() {
    tmp_82_trn_fu_465_p1 = esl_zext<32,3>(tmp_63_fu_455_p4.read());
}

void dateport_DC3_layer::thread_tmp_83_trn_fu_474_p1() {
    tmp_83_trn_fu_474_p1 = esl_zext<32,4>(k_reg_196.read());
}

void dateport_DC3_layer::thread_tmp_87_fu_330_p4() {
    tmp_87_fu_330_p4 = j_reg_184.read().range(3, 1);
}

void dateport_DC3_layer::thread_tmp_87_trn_fu_494_p1() {
    tmp_87_trn_fu_494_p1 = esl_zext<32,4>(tmp_66_fu_488_p2.read());
}

void dateport_DC3_layer::thread_tmp_88_fu_353_p3() {
    tmp_88_fu_353_p3 = esl_concat<8,2>(S4_d_addr13_fu_344_p2.read(), ap_const_lv2_0);
}

void dateport_DC3_layer::thread_tmp_89_fu_380_p3() {
    tmp_89_fu_380_p3 = esl_concat<9,3>(C3_y_addr6_fu_375_p2.read(), ap_const_lv3_0);
}

void dateport_DC3_layer::thread_tmp_90_fu_392_p3() {
    tmp_90_fu_392_p3 = esl_concat<9,1>(C3_y_addr6_fu_375_p2.read(), ap_const_lv1_0);
}

void dateport_DC3_layer::thread_tmp_91_fu_419_p3() {
    tmp_91_fu_419_p3 = esl_concat<9,3>(C3_y_addr8_fu_414_p2.read(), ap_const_lv3_0);
}

void dateport_DC3_layer::thread_tmp_92_fu_431_p3() {
    tmp_92_fu_431_p3 = esl_concat<9,1>(C3_y_addr8_fu_414_p2.read(), ap_const_lv1_0);
}

void dateport_DC3_layer::thread_tmp_93_fu_556_p1() {
    tmp_93_fu_556_p1 = temp_to_int_fu_542_p1.read().range(23-1, 0);
}

void dateport_DC3_layer::thread_tmp_94_fu_598_p1() {
    tmp_94_fu_598_p1 = temp_3_to_int_fu_584_p1.read().range(23-1, 0);
}

void dateport_DC3_layer::thread_tmp_95_fu_656_p1() {
    tmp_95_fu_656_p1 = temp_4_to_int_fu_642_p1.read().range(23-1, 0);
}

void dateport_DC3_layer::thread_tmp_96_fu_698_p1() {
    tmp_96_fu_698_p1 = temp_5_to_int_fu_684_p1.read().range(23-1, 0);
}

void dateport_DC3_layer::thread_tmp_fu_261_p1() {
    tmp_fu_261_p1 = esl_zext<64,5>(i_reg_172.read());
}

void dateport_DC3_layer::thread_tmp_s_fu_318_p2() {
    tmp_s_fu_318_p2 = (!j_reg_184.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): (sc_biguint<4>(j_reg_184.read()) < sc_biguint<4>(ap_const_lv4_A));
}

void dateport_DC3_layer::thread_tmp_trn_cast_fu_266_p1() {
    tmp_trn_cast_fu_266_p1 = esl_zext<8,5>(i_reg_172.read());
}

void dateport_DC3_layer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond_fu_249_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_318_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_62_fu_449_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

