// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _dateport_S2_pool_HH_
#define _dateport_S2_pool_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dateport_fadd_32ns_32ns_32_5_full_dsp.h"
#include "dateport_fmul_32ns_32ns_32_4_max_dsp.h"

namespace ap_rtl {

struct dateport_S2_pool : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > C1_y_address0;
    sc_out< sc_logic > C1_y_ce0;
    sc_in< sc_lv<32> > C1_y_q0;
    sc_out< sc_lv<13> > C1_y_address1;
    sc_out< sc_logic > C1_y_ce1;
    sc_in< sc_lv<32> > C1_y_q1;
    sc_out< sc_lv<11> > S2_y_address0;
    sc_out< sc_logic > S2_y_ce0;
    sc_out< sc_logic > S2_y_we0;
    sc_out< sc_lv<32> > S2_y_d0;


    // Module declarations
    dateport_S2_pool(sc_module_name name);
    SC_HAS_PROCESS(dateport_S2_pool);

    ~dateport_S2_pool();

    sc_trace_file* mVcdFile;

    dateport_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>* dateport_fadd_32ns_32ns_32_5_full_dsp_U8;
    dateport_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>* dateport_fmul_32ns_32ns_32_4_max_dsp_U9;
    sc_signal< sc_lv<24> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_42;
    sc_signal< sc_lv<32> > reg_151;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_69;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_bdd_76;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_14;
    sc_signal< bool > ap_sig_bdd_84;
    sc_signal< sc_lv<32> > grp_fu_141_p2;
    sc_signal< sc_lv<32> > reg_158;
    sc_signal< sc_logic > ap_sig_cseq_ST_st20_fsm_19;
    sc_signal< bool > ap_sig_bdd_94;
    sc_signal< sc_lv<3> > i_1_fu_170_p2;
    sc_signal< sc_lv<3> > i_1_reg_479;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_104;
    sc_signal< sc_lv<10> > C1_y_addr1_cast_fu_206_p1;
    sc_signal< sc_lv<10> > C1_y_addr1_cast_reg_484;
    sc_signal< sc_lv<1> > exitcond_fu_164_p2;
    sc_signal< sc_lv<9> > S2_y_addr1_cast_fu_240_p1;
    sc_signal< sc_lv<9> > S2_y_addr1_cast_reg_490;
    sc_signal< sc_lv<32> > C1_y_addr3_fu_289_p2;
    sc_signal< sc_lv<32> > C1_y_addr3_reg_498;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_121;
    sc_signal< sc_lv<1> > tmp_s_fu_244_p2;
    sc_signal< sc_lv<32> > C1_y_addr9_fu_328_p2;
    sc_signal< sc_lv<32> > C1_y_addr9_reg_504;
    sc_signal< sc_lv<32> > S2_y_addr3_fu_377_p2;
    sc_signal< sc_lv<32> > S2_y_addr3_reg_510;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_138;
    sc_signal< sc_lv<1> > tmp_9_fu_383_p2;
    sc_signal< sc_lv<32> > C1_y_addr7_fu_423_p2;
    sc_signal< sc_lv<32> > C1_y_addr7_reg_528;
    sc_signal< sc_lv<32> > C1_y_addr4_fu_428_p2;
    sc_signal< sc_lv<32> > C1_y_addr4_reg_533;
    sc_signal< sc_lv<32> > S2_y_addr4_fu_447_p2;
    sc_signal< sc_lv<32> > S2_y_addr4_reg_538;
    sc_signal< sc_lv<5> > k_1_fu_452_p2;
    sc_signal< sc_lv<5> > k_1_reg_543;
    sc_signal< sc_lv<5> > j_1_fu_458_p2;
    sc_signal< sc_lv<32> > C1_y_load_1_reg_553;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_bdd_165;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_13;
    sc_signal< bool > ap_sig_bdd_174;
    sc_signal< sc_lv<3> > i_reg_107;
    sc_signal< sc_lv<5> > j_reg_118;
    sc_signal< sc_lv<5> > k_reg_130;
    sc_signal< sc_logic > ap_sig_cseq_ST_st24_fsm_23;
    sc_signal< bool > ap_sig_bdd_193;
    sc_signal< sc_lv<64> > tmp_30_fu_398_p1;
    sc_signal< sc_lv<64> > tmp_31_fu_418_p1;
    sc_signal< sc_lv<64> > tmp_32_fu_464_p1;
    sc_signal< sc_lv<64> > tmp_33_fu_468_p1;
    sc_signal< sc_lv<64> > tmp_34_fu_472_p1;
    sc_signal< sc_lv<32> > grp_fu_145_p2;
    sc_signal< sc_lv<32> > grp_fu_141_p0;
    sc_signal< sc_lv<32> > grp_fu_141_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_212;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_bdd_219;
    sc_signal< sc_logic > ap_sig_cseq_ST_st16_fsm_15;
    sc_signal< bool > ap_sig_bdd_226;
    sc_signal< sc_lv<32> > grp_fu_145_p0;
    sc_signal< sc_lv<32> > grp_fu_145_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st21_fsm_20;
    sc_signal< bool > ap_sig_bdd_237;
    sc_signal< sc_lv<8> > tmp_fu_176_p3;
    sc_signal< sc_lv<5> > tmp_21_fu_188_p3;
    sc_signal< sc_lv<9> > p_shl1_cast_fu_184_p1;
    sc_signal< sc_lv<9> > p_shl2_cast_fu_196_p1;
    sc_signal< sc_lv<9> > C1_y_addr1_fu_200_p2;
    sc_signal< sc_lv<7> > tmp_22_fu_210_p3;
    sc_signal< sc_lv<4> > tmp_23_fu_222_p3;
    sc_signal< sc_lv<8> > p_shl_cast_fu_218_p1;
    sc_signal< sc_lv<8> > p_shl3_cast_fu_230_p1;
    sc_signal< sc_lv<8> > S2_y_addr1_fu_234_p2;
    sc_signal< sc_lv<10> > tmp_4_trn_cast_fu_256_p1;
    sc_signal< sc_lv<10> > C1_y_addr2_fu_260_p2;
    sc_signal< sc_lv<15> > tmp_24_fu_265_p3;
    sc_signal< sc_lv<12> > tmp_25_fu_277_p3;
    sc_signal< sc_lv<32> > p_shl4_fu_273_p1;
    sc_signal< sc_lv<32> > p_shl5_fu_285_p1;
    sc_signal< sc_lv<5> > tmp_5_fu_250_p2;
    sc_signal< sc_lv<10> > tmp_6_trn6_cast_fu_295_p1;
    sc_signal< sc_lv<10> > C1_y_addr8_fu_299_p2;
    sc_signal< sc_lv<15> > tmp_26_fu_304_p3;
    sc_signal< sc_lv<12> > tmp_27_fu_316_p3;
    sc_signal< sc_lv<32> > p_shl6_fu_312_p1;
    sc_signal< sc_lv<32> > p_shl7_fu_324_p1;
    sc_signal< sc_lv<4> > tmp_28_fu_334_p4;
    sc_signal< sc_lv<9> > tmp_8_trn_cast_fu_344_p1;
    sc_signal< sc_lv<9> > S2_y_addr2_fu_348_p2;
    sc_signal< sc_lv<13> > tmp_29_fu_353_p3;
    sc_signal< sc_lv<10> > tmp_35_fu_365_p3;
    sc_signal< sc_lv<32> > p_shl8_fu_361_p1;
    sc_signal< sc_lv<32> > p_shl9_fu_373_p1;
    sc_signal< sc_lv<32> > tmp_10_trn_fu_389_p1;
    sc_signal< sc_lv<32> > C1_y_addr5_fu_393_p2;
    sc_signal< sc_lv<5> > tmp_11_fu_403_p2;
    sc_signal< sc_lv<32> > tmp_12_trn_fu_409_p1;
    sc_signal< sc_lv<32> > C1_y_addr6_fu_413_p2;
    sc_signal< sc_lv<4> > tmp_17_fu_433_p4;
    sc_signal< sc_lv<32> > tmp_18_trn_fu_443_p1;
    sc_signal< sc_logic > grp_fu_141_ce;
    sc_signal< sc_logic > grp_fu_145_ce;
    sc_signal< sc_lv<24> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_ST_st1_fsm_0;
    static const sc_lv<24> ap_ST_st2_fsm_1;
    static const sc_lv<24> ap_ST_st3_fsm_2;
    static const sc_lv<24> ap_ST_st4_fsm_3;
    static const sc_lv<24> ap_ST_st5_fsm_4;
    static const sc_lv<24> ap_ST_st6_fsm_5;
    static const sc_lv<24> ap_ST_st7_fsm_6;
    static const sc_lv<24> ap_ST_st8_fsm_7;
    static const sc_lv<24> ap_ST_st9_fsm_8;
    static const sc_lv<24> ap_ST_st10_fsm_9;
    static const sc_lv<24> ap_ST_st11_fsm_10;
    static const sc_lv<24> ap_ST_st12_fsm_11;
    static const sc_lv<24> ap_ST_st13_fsm_12;
    static const sc_lv<24> ap_ST_st14_fsm_13;
    static const sc_lv<24> ap_ST_st15_fsm_14;
    static const sc_lv<24> ap_ST_st16_fsm_15;
    static const sc_lv<24> ap_ST_st17_fsm_16;
    static const sc_lv<24> ap_ST_st18_fsm_17;
    static const sc_lv<24> ap_ST_st19_fsm_18;
    static const sc_lv<24> ap_ST_st20_fsm_19;
    static const sc_lv<24> ap_ST_st21_fsm_20;
    static const sc_lv<24> ap_ST_st22_fsm_21;
    static const sc_lv<24> ap_ST_st23_fsm_22;
    static const sc_lv<24> ap_ST_st24_fsm_23;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_3E800000;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<5> ap_const_lv5_1C;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_C1_y_addr1_cast_fu_206_p1();
    void thread_C1_y_addr1_fu_200_p2();
    void thread_C1_y_addr2_fu_260_p2();
    void thread_C1_y_addr3_fu_289_p2();
    void thread_C1_y_addr4_fu_428_p2();
    void thread_C1_y_addr5_fu_393_p2();
    void thread_C1_y_addr6_fu_413_p2();
    void thread_C1_y_addr7_fu_423_p2();
    void thread_C1_y_addr8_fu_299_p2();
    void thread_C1_y_addr9_fu_328_p2();
    void thread_C1_y_address0();
    void thread_C1_y_address1();
    void thread_C1_y_ce0();
    void thread_C1_y_ce1();
    void thread_S2_y_addr1_cast_fu_240_p1();
    void thread_S2_y_addr1_fu_234_p2();
    void thread_S2_y_addr2_fu_348_p2();
    void thread_S2_y_addr3_fu_377_p2();
    void thread_S2_y_addr4_fu_447_p2();
    void thread_S2_y_address0();
    void thread_S2_y_ce0();
    void thread_S2_y_d0();
    void thread_S2_y_we0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_104();
    void thread_ap_sig_bdd_121();
    void thread_ap_sig_bdd_138();
    void thread_ap_sig_bdd_165();
    void thread_ap_sig_bdd_174();
    void thread_ap_sig_bdd_193();
    void thread_ap_sig_bdd_212();
    void thread_ap_sig_bdd_219();
    void thread_ap_sig_bdd_226();
    void thread_ap_sig_bdd_237();
    void thread_ap_sig_bdd_42();
    void thread_ap_sig_bdd_69();
    void thread_ap_sig_bdd_76();
    void thread_ap_sig_bdd_84();
    void thread_ap_sig_bdd_94();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st14_fsm_13();
    void thread_ap_sig_cseq_ST_st15_fsm_14();
    void thread_ap_sig_cseq_ST_st16_fsm_15();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st20_fsm_19();
    void thread_ap_sig_cseq_ST_st21_fsm_20();
    void thread_ap_sig_cseq_ST_st24_fsm_23();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_exitcond_fu_164_p2();
    void thread_grp_fu_141_ce();
    void thread_grp_fu_141_p0();
    void thread_grp_fu_141_p1();
    void thread_grp_fu_145_ce();
    void thread_grp_fu_145_p0();
    void thread_grp_fu_145_p1();
    void thread_i_1_fu_170_p2();
    void thread_j_1_fu_458_p2();
    void thread_k_1_fu_452_p2();
    void thread_p_shl1_cast_fu_184_p1();
    void thread_p_shl2_cast_fu_196_p1();
    void thread_p_shl3_cast_fu_230_p1();
    void thread_p_shl4_fu_273_p1();
    void thread_p_shl5_fu_285_p1();
    void thread_p_shl6_fu_312_p1();
    void thread_p_shl7_fu_324_p1();
    void thread_p_shl8_fu_361_p1();
    void thread_p_shl9_fu_373_p1();
    void thread_p_shl_cast_fu_218_p1();
    void thread_tmp_10_trn_fu_389_p1();
    void thread_tmp_11_fu_403_p2();
    void thread_tmp_12_trn_fu_409_p1();
    void thread_tmp_17_fu_433_p4();
    void thread_tmp_18_trn_fu_443_p1();
    void thread_tmp_21_fu_188_p3();
    void thread_tmp_22_fu_210_p3();
    void thread_tmp_23_fu_222_p3();
    void thread_tmp_24_fu_265_p3();
    void thread_tmp_25_fu_277_p3();
    void thread_tmp_26_fu_304_p3();
    void thread_tmp_27_fu_316_p3();
    void thread_tmp_28_fu_334_p4();
    void thread_tmp_29_fu_353_p3();
    void thread_tmp_30_fu_398_p1();
    void thread_tmp_31_fu_418_p1();
    void thread_tmp_32_fu_464_p1();
    void thread_tmp_33_fu_468_p1();
    void thread_tmp_34_fu_472_p1();
    void thread_tmp_35_fu_365_p3();
    void thread_tmp_4_trn_cast_fu_256_p1();
    void thread_tmp_5_fu_250_p2();
    void thread_tmp_6_trn6_cast_fu_295_p1();
    void thread_tmp_8_trn_cast_fu_344_p1();
    void thread_tmp_9_fu_383_p2();
    void thread_tmp_fu_176_p3();
    void thread_tmp_s_fu_244_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
