lappend pragmaStatus0 {pragma "INTERFACE" source "D:/vivado_hls/Le_7/Lnet.c" location "dateport" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "D:/vivado_hls/Le_7/Lnet.c" location "dateport" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "D:/vivado_hls/Le_7/Lnet.c" location "dateport" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "D:/vivado_hls/Le_7/Lnet.c" location "dateport" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "D:/vivado_hls/Le_7/Lnet.c" location "dateport" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C1_conv/C1_conv_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C1_conv/C1_conv_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C1_conv/C1_conv_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C1_conv/C1_conv_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C3_conv/C3_conv_label4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C3_conv/C3_conv_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "C5_conv/C5_conv_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "DS4_layer/DS4_layer_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "DS4_layer/DS4_layer_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "DS2_layer/DS2_layer_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "DS2_layer/DS2_layer_label4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "update_C1/update_C1_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "update_C1/update_C1_label5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus18 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "update_C3/update_C3_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus19 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "update_C3/update_C3_label6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus20 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "update_C5/update_C5_label7" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus21 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "update_C5/update_C5_label8" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus22 {pragma "PIPELINE" source "D:/vivado_hls/Le_7/Lnet.c" location "upadteall/upadteall_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
